/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// deno-lint-ignore-file

import Axios, { type AxiosPromise, type AxiosRequestConfig } from "axios";

export const axios = Axios.create({
  baseURL: '',
  paramsSerializer: (params: any) =>
    encodeParams(params, null, {
      allowDots: true,
      arrayFormat: 'repeat',
    }),
});

export const petClient = {
    /**
   * Add a new pet to the store
   * @param body  
   */
  addPet(body: Pet ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Pet> {
    const url = `/pet`;

    return axios.request<Pet>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

  /**
   * Deletes a pet
   * @param apiKey (optional) (API name: api_key)
   * @param petId  
   */
  deletePet(apiKey: string | null | undefined,
    petId: number ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<unknown> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;

    return axios.request<unknown>({
      url: url,
      method: 'DELETE',
      headers: {
        'api_key': apiKey,
      },
      ...$config,
    });
  },

  /**
   * Finds Pets by status
   * Multiple status values can be provided with comma separated strings
   * @param status (optional) 
   */
  findPetsByStatus(status?: ("available" | "pending" | "sold") | null,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Pet[]> {
    const url = `/pet/findByStatus`;

    return axios.request<Pet[]>({
      url: url,
      method: 'GET',
      params: {
        'status': status,
      },
      ...$config,
    });
  },

  /**
   * Finds Pets by tags
   * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
   * @deprecated
   * @param tags (optional) 
   */
  findPetsByTags(tags?: string[] | null,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Pet[]> {
    const url = `/pet/findByTags`;

    return axios.request<Pet[]>({
      url: url,
      method: 'GET',
      params: {
        'tags': tags,
      },
      ...$config,
    });
  },

  /**
   * Find pet by ID
   * Returns a single pet
   * @param petId  
   */
  getPetById(petId: number ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Pet> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;

    return axios.request<Pet>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

  /**
   * Update an existing pet
   * Update an existing pet by Id
   * @param body  
   */
  updatePet(body: Pet ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Pet> {
    const url = `/pet`;

    return axios.request<Pet>({
      url: url,
      method: 'PUT',
      data: new URLSearchParams(body as any),
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      ...$config,
    });
  },

  /**
   * Updates a pet in the store with form data
   * @param petId  
   * @param name (optional) 
   * @param status (optional) 
   */
  updatePetWithForm(petId: number ,
    name?: string | null,
    status?: string | null,
    $config?: AxiosRequestConfig
  ): AxiosPromise<unknown> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;

    return axios.request<unknown>({
      url: url,
      method: 'POST',
      params: {
        'name': name,
        'status': status,
      },
      ...$config,
    });
  },

  /**
   * uploads an image
   * @param body (optional) 
   * @param petId  
   * @param additionalMetadata (optional) 
   */
  uploadFile(body: File | null | undefined,
    petId: number ,
    additionalMetadata?: string | null,
    $config?: AxiosRequestConfig
  ): AxiosPromise<File> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}/uploadImage`;

    return axios.request<File>({
      url: url,
      method: 'POST',
      data: body,
      params: {
        'additionalMetadata': additionalMetadata,
      },
      ...$config,
    });
  },

};

export const storeClient = {
    /**
   * Delete purchase order by ID
   * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
   * @param orderId  
   */
  deleteOrder(orderId: number ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<unknown> {
    const url = `/store/order/${encodeURIComponent(`${orderId}`)}`;

    return axios.request<unknown>({
      url: url,
      method: 'DELETE',
      ...$config,
    });
  },

  getInventory($config?: AxiosRequestConfig
  ): AxiosPromise<{ [key: string]: number }> {
    const url = `/store/inventory`;

    return axios.request<{ [key: string]: number }>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

  /**
   * Find purchase order by ID
   * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
   * @param orderId  
   */
  getOrderById(orderId: number ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Order> {
    const url = `/store/order/${encodeURIComponent(`${orderId}`)}`;

    return axios.request<Order>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

  /**
   * Place an order for a pet
   * Place a new order in the store
   * @param body (optional) 
   */
  placeOrder(body?: Order | null,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Order> {
    const url = `/store/order`;

    return axios.request<Order>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

};

export const userClient = {
    /**
   * Create user
   * This can only be done by the logged in user.
   * @param body (optional) 
   */
  createUser(body?: User | null,
    $config?: AxiosRequestConfig
  ): AxiosPromise<User> {
    const url = `/user`;

    return axios.request<User>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

  /**
   * Creates list of users with given input array
   * @param body (optional) 
   */
  createUsersWithListInput(body?: User[] | null,
    $config?: AxiosRequestConfig
  ): AxiosPromise<User> {
    const url = `/user/createWithList`;

    return axios.request<User>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

  /**
   * Delete user
   * This can only be done by the logged in user.
   * @param username  
   */
  deleteUser(username: string ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<unknown> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;

    return axios.request<unknown>({
      url: url,
      method: 'DELETE',
      ...$config,
    });
  },

  /**
   * Get user by user name
   * @param username  
   */
  getUserByName(username: string ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<User> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;

    return axios.request<User>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

  /**
   * Logs user into the system
   * @param username (optional) 
   * @param password (optional) 
   */
  loginUser(username?: string | null,
    password?: string | null,
    $config?: AxiosRequestConfig
  ): AxiosPromise<string> {
    const url = `/user/login`;

    return axios.request<string>({
      url: url,
      method: 'GET',
      params: {
        'username': username,
        'password': password,
      },
      ...$config,
    });
  },

  logoutUser($config?: AxiosRequestConfig
  ): AxiosPromise<unknown> {
    const url = `/user/logout`;

    return axios.request<unknown>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

  /**
   * Update user
   * This can only be done by the logged in user.
   * @param body (optional) 
   * @param username  
   */
  updateUser(body: FormData | null | undefined,
    username: string ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<unknown> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;

    return axios.request<unknown>({
      url: url,
      method: 'PUT',
      data: body,
      ...$config,
    });
  },

};


/**
 * Serializes a params object into a query string that is compatible with different REST APIs.
 * Implementation from: https://github.com/suhaotian/xior/blob/main/src/utils.ts
 * Kudos to @suhaotian for the original implementation
 */
function encodeParams<T = any>(
  params: T,
  parentKey: string | null = null,
  options?: {
    allowDots?: boolean;
    serializeDate?: (value: Date) => string;
    arrayFormat?: 'indices' | 'repeat' | 'brackets';
  }
): string {
  if (params === undefined || params === null) return '';
  const encodedParams: string[] = [];
  const paramsIsArray = Array.isArray(params);
  const { arrayFormat, allowDots, serializeDate } = options || {};

  const getKey = (key: string) => {
    if (allowDots && !paramsIsArray) return `.${key}`;
    if (paramsIsArray) {
      if (arrayFormat === 'brackets') {
        return '[]';
      }
      if (arrayFormat === 'repeat') {
        return '';
      }
    }
    return `[${key}]`;
  };

  for (const key in params) {
    if (Object.prototype.hasOwnProperty.call(params, key)) {
      let value = (params as any)[key];
      if (value !== undefined) {
        const encodedKey = parentKey ? `${parentKey}${getKey(key)}` : (key as string);

        // biome-ignore lint/suspicious/noGlobalIsNan: <explanation>
        if (!isNaN(value) && value instanceof Date) {
          value = serializeDate ? serializeDate(value) : value.toISOString();
        }
        if (typeof value === 'object') {
          // If the value is an object or array, recursively encode its contents
          const result = encodeParams(value, encodedKey, options);
          if (result !== '') encodedParams.push(result);
        } else {
          // Otherwise, encode the key-value pair
          encodedParams.push(`${encodeURIComponent(encodedKey)}=${encodeURIComponent(value)}`);
        }
      }
    }
  }

  return encodedParams.join('&');
}

export interface Order {
  id?: number;
  petId?: number;
  quantity?: number;
  shipDate?: Date;
/** Order Status */
  status?: ("placed" | "approved" | "delivered");
  complete?: boolean;}

export interface Category {
  id?: number;
  name?: string;}

export interface User {
  id?: number;
  username?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  password?: string;
  phone?: string;
/** User Status */
  userStatus?: number;}

export interface Tag {
  id?: number;
  name?: string;}

export interface Pet {
  id?: number;
  name: string;
  category?: Category;
  photoUrls: string[];
  tags?: Tag[];
/** pet status in the store */
  status?: ("available" | "pending" | "sold");}
