/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// deno-lint-ignore-file

import Axios, { type AxiosPromise, AxiosRequestConfig } from "axios";

export const axios = Axios.create({
  baseURL: '',
  paramsSerializer: (params: any) => paramsSerializer(params),
});

export const petClient = {
    /**
   * @param body  
   */
  addPet(body: Pet ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Pet> {
    const url = `/pet`;

    return axios.request<Pet>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

  /**
   * @param apiKey (optional) (API name: api_key)
   * @param petId  
   */
  deletePet(apiKey: string | null | undefined,
    petId: number ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<unknown> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;

    return axios.request<unknown>({
      url: url,
      method: 'DELETE',
      headers: {
        'api_key': apiKey,
      },
      ...$config,
    });
  },

  /**
   * @param status (optional) 
   */
  findPetsByStatus(status: ("available" | "pending" | "sold") | null | undefined,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Pet[]> {
    const url = `/pet/findByStatus`;

    return axios.request<Pet[]>({
      url: url,
      method: 'GET',
      params: {
        'status': status,
      },
      ...$config,
    });
  },

  /**
   * @param tags (optional) 
   */
  findPetsByTags(tags: string[] | null | undefined,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Pet[]> {
    const url = `/pet/findByTags`;

    return axios.request<Pet[]>({
      url: url,
      method: 'GET',
      params: {
        'tags': tags,
      },
      ...$config,
    });
  },

  /**
   * @param petId  
   */
  getPetById(petId: number ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Pet> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;

    return axios.request<Pet>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

  /**
   * @param body  
   */
  updatePet(body: Pet ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Pet> {
    const url = `/pet`;

    return axios.request<Pet>({
      url: url,
      method: 'PUT',
      data: new URLSearchParams(body as any),
      ...$config,
    });
  },

  /**
   * @param petId  
   * @param name (optional) 
   * @param status (optional) 
   */
  updatePetWithForm(petId: number ,
    name: string | null | undefined,
    status: string | null | undefined,
    $config?: AxiosRequestConfig
  ): AxiosPromise<unknown> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;

    return axios.request<unknown>({
      url: url,
      method: 'POST',
      params: {
        'name': name,
        'status': status,
      },
      ...$config,
    });
  },

  /**
   * @param body (optional) 
   * @param petId  
   * @param additionalMetadata (optional) 
   */
  uploadFile(body: File | null | undefined,
    petId: number ,
    additionalMetadata: string | null | undefined,
    $config?: AxiosRequestConfig
  ): AxiosPromise<File> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}/uploadImage`;

    return axios.request<File>({
      url: url,
      method: 'POST',
      data: body,
      params: {
        'additionalMetadata': additionalMetadata,
      },
      ...$config,
    });
  },

};

export const storeClient = {
    /**
   * @param orderId  
   */
  deleteOrder(orderId: number ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<unknown> {
    const url = `/store/order/${encodeURIComponent(`${orderId}`)}`;

    return axios.request<unknown>({
      url: url,
      method: 'DELETE',
      ...$config,
    });
  },

  /**
   */
  getInventory($config?: AxiosRequestConfig
  ): AxiosPromise<{ [key: string]: number }> {
    const url = `/store/inventory`;

    return axios.request<{ [key: string]: number }>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

  /**
   * @param orderId  
   */
  getOrderById(orderId: number ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Order> {
    const url = `/store/order/${encodeURIComponent(`${orderId}`)}`;

    return axios.request<Order>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

  /**
   * @param body (optional) 
   */
  placeOrder(body: Order | null | undefined,
    $config?: AxiosRequestConfig
  ): AxiosPromise<Order> {
    const url = `/store/order`;

    return axios.request<Order>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

};

export const userClient = {
    /**
   * @param body (optional) 
   */
  createUser(body: User | null | undefined,
    $config?: AxiosRequestConfig
  ): AxiosPromise<User> {
    const url = `/user`;

    return axios.request<User>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

  /**
   * @param body (optional) 
   */
  createUsersWithListInput(body: User[] | null | undefined,
    $config?: AxiosRequestConfig
  ): AxiosPromise<User> {
    const url = `/user/createWithList`;

    return axios.request<User>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

  /**
   * @param username  
   */
  deleteUser(username: string ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<unknown> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;

    return axios.request<unknown>({
      url: url,
      method: 'DELETE',
      ...$config,
    });
  },

  /**
   * @param username  
   */
  getUserByName(username: string ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<User> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;

    return axios.request<User>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

  /**
   * @param username (optional) 
   * @param password (optional) 
   */
  loginUser(username: string | null | undefined,
    password: string | null | undefined,
    $config?: AxiosRequestConfig
  ): AxiosPromise<string> {
    const url = `/user/login`;

    return axios.request<string>({
      url: url,
      method: 'GET',
      params: {
        'username': username,
        'password': password,
      },
      ...$config,
    });
  },

  /**
   */
  logoutUser($config?: AxiosRequestConfig
  ): AxiosPromise<unknown> {
    const url = `/user/logout`;

    return axios.request<unknown>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

  /**
   * @param body (optional) 
   * @param username  
   */
  updateUser(body: FormData | null | undefined,
    username: string ,
    $config?: AxiosRequestConfig
  ): AxiosPromise<unknown> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;

    return axios.request<unknown>({
      url: url,
      method: 'PUT',
      data: body,
      ...$config,
    });
  },

};


function paramsSerializer<T = any>(params: T, parentKey: string | null = null): string {
  if (params === undefined || params === null) return '';
  const encodedParams: string[] = [];
  const encodeValue = (value: any) =>
    encodeURIComponent(value instanceof Date && !Number.isNaN(value) ? value.toISOString() : value);

  for (const key in params) {
    if (Object.prototype.hasOwnProperty.call(params, key)) {
      const value = (params as any)[key];
      if (value !== undefined) {
        const fullKey = parentKey ? `${parentKey}.${key}` : key;

        if (Array.isArray(value)) {
          for (const element of value) {
            encodedParams.push(`${encodeURIComponent(fullKey)}=${encodeValue(element)}`);
          }
        } else if (value instanceof Date && !Number.isNaN(value)) {
          // If the value is a Date, convert it to ISO format
          encodedParams.push(`${encodeURIComponent(fullKey)}=${encodeValue(value)}`);
        } else if (typeof value === 'object') {
          // If the value is an object or array, recursively encode its contents
          const result = paramsSerializer(value, fullKey);
          if (result !== '') encodedParams.push(result);
        } else {
          // Otherwise, encode the key-value pair
          encodedParams.push(`${encodeURIComponent(fullKey)}=${encodeValue(value)}`);
        }
      }
    }
  }

  return encodedParams.join('&');
}

export interface Order {
  id?: number;
  petId?: number;
  quantity?: number;
  shipDate?: Date;
// Order Status
  status?: ("placed" | "approved" | "delivered");
  complete?: boolean;}

export interface Customer {
  id?: number;
  username?: string;
  address?: Address[];}

export interface Address {
  street?: string;
  city?: string;
  state?: string;
  zip?: string;}

export interface Category {
  id?: number;
  name?: string;}

export interface User {
  id?: number;
  username?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  password?: string;
  phone?: string;
// User Status
  userStatus?: number;}

export interface Tag {
  id?: number;
  name?: string;}

export interface Pet {
  id?: number;
  name: string;
  category?: Category;
  photoUrls: string[];
  tags?: Tag[];
// pet status in the store
  status?: ("available" | "pending" | "sold");}

export interface ApiResponse {
  code?: number;
  type?: string;
  message?: string;}
