/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// deno-lint-ignore-file

export const defaults = {
  baseUrl: '',
};

export const petClient = {
    /**
   * @param body  
   */
  addPet(body: Pet ,
    $config?: RequestInit
  ): Promise<unknown> {
    let url = defaults.baseUrl + '/pet?';

    return fetch(url, {
      method: 'POST',
      body: JSON.stringify(body),
      ...$config,
    }).then((response) => response.json() as Promise<unknown>);
  },

  /**
   * @param apiKey (optional) (API name: api_key)
   * @param petId  
   */
  deletePet(apiKey: string | null | undefined,
    petId: number ,
    $config?: RequestInit
  ): Promise<unknown> {
    let url = defaults.baseUrl + '/pet/{petId}?';
    url = url.replace('{petId}', encodeURIComponent("" + petId));

    return fetch(url, {
      method: 'DELETE',
      headers: {
        'api_key': apiKey,
      },
      ...$config,
    }).then((response) => response.json() as Promise<unknown>);
  },

  /**
   * @param status  
   */
  findPetsByStatus(status: ('available'|'pending'|'sold')[] ,
    $config?: RequestInit
  ): Promise<Pet[]> {
    let url = defaults.baseUrl + '/pet/findByStatus?';
    if (status !== undefined) {
      status.forEach(item => { url += 'status=' + serializeQueryParam(item) + "&"; });
    }
  
    return fetch(url, {
      method: 'GET',
      ...$config,
    }).then((response) => response.json() as Promise<Pet[]>);
  },

  /**
   * @param tags  
   */
  findPetsByTags(tags: string[] ,
    $config?: RequestInit
  ): Promise<Pet[]> {
    let url = defaults.baseUrl + '/pet/findByTags?';
    if (tags !== undefined) {
      tags.forEach(item => { url += 'tags=' + serializeQueryParam(item) + "&"; });
    }
  
    return fetch(url, {
      method: 'GET',
      ...$config,
    }).then((response) => response.json() as Promise<Pet[]>);
  },

  /**
   * @param petId  
   */
  getPetById(petId: number ,
    $config?: RequestInit
  ): Promise<Pet> {
    let url = defaults.baseUrl + '/pet/{petId}?';
    url = url.replace('{petId}', encodeURIComponent("" + petId));

    return fetch(url, {
      method: 'GET',
      ...$config,
    }).then((response) => response.json() as Promise<Pet>);
  },

  /**
   * @param body  
   */
  updatePet(body: Pet ,
    $config?: RequestInit
  ): Promise<unknown> {
    let url = defaults.baseUrl + '/pet?';

    return fetch(url, {
      method: 'PUT',
      body: JSON.stringify(body),
      ...$config,
    }).then((response) => response.json() as Promise<unknown>);
  },

  /**
   * @param petId  
   * @param name (optional) 
   * @param status (optional) 
   */
  updatePetWithForm(petId: number ,
    name: string | null | undefined,
    status: string | null | undefined,
    $config?: RequestInit
  ): Promise<unknown> {
    let url = defaults.baseUrl + '/pet/{petId}?';
    url = url.replace('{petId}', encodeURIComponent("" + petId));

    return fetch(url, {
      method: 'POST',
      ...$config,
    }).then((response) => response.json() as Promise<unknown>);
  },

  /**
   * @param petId  
   * @param additionalMetadata (optional) 
   * @param file (optional) 
   */
  uploadFile(petId: number ,
    additionalMetadata: string | null | undefined,
    file: File | null | undefined,
    $config?: RequestInit
  ): Promise<ApiResponse> {
    let url = defaults.baseUrl + '/pet/{petId}/uploadImage?';
    url = url.replace('{petId}', encodeURIComponent("" + petId));

    return fetch(url, {
      method: 'POST',
      ...$config,
    }).then((response) => response.json() as Promise<ApiResponse>);
  },

};
export const storeClient = {
    /**
   * @param orderId  
   */
  deleteOrder(orderId: number ,
    $config?: RequestInit
  ): Promise<unknown> {
    let url = defaults.baseUrl + '/store/order/{orderId}?';
    url = url.replace('{orderId}', encodeURIComponent("" + orderId));

    return fetch(url, {
      method: 'DELETE',
      ...$config,
    }).then((response) => response.json() as Promise<unknown>);
  },

  /**
   */
  getInventory($config?: RequestInit
  ): Promise<{ [key: string]: number }> {
    let url = defaults.baseUrl + '/store/inventory?';

    return fetch(url, {
      method: 'GET',
      ...$config,
    }).then((response) => response.json() as Promise<{ [key: string]: number }>);
  },

  /**
   * @param orderId  
   */
  getOrderById(orderId: number ,
    $config?: RequestInit
  ): Promise<Order> {
    let url = defaults.baseUrl + '/store/order/{orderId}?';
    url = url.replace('{orderId}', encodeURIComponent("" + orderId));

    return fetch(url, {
      method: 'GET',
      ...$config,
    }).then((response) => response.json() as Promise<Order>);
  },

  /**
   * @param body  
   */
  placeOrder(body: Order ,
    $config?: RequestInit
  ): Promise<Order> {
    let url = defaults.baseUrl + '/store/order?';

    return fetch(url, {
      method: 'POST',
      body: JSON.stringify(body),
      ...$config,
    }).then((response) => response.json() as Promise<Order>);
  },

};
export const userClient = {
    /**
   * @param body  
   */
  createUser(body: User ,
    $config?: RequestInit
  ): Promise<unknown> {
    let url = defaults.baseUrl + '/user?';

    return fetch(url, {
      method: 'POST',
      body: JSON.stringify(body),
      ...$config,
    }).then((response) => response.json() as Promise<unknown>);
  },

  /**
   * @param body  
   */
  createUsersWithArrayInput(body: User[] ,
    $config?: RequestInit
  ): Promise<unknown> {
    let url = defaults.baseUrl + '/user/createWithArray?';

    return fetch(url, {
      method: 'POST',
      body: JSON.stringify(body),
      ...$config,
    }).then((response) => response.json() as Promise<unknown>);
  },

  /**
   * @param body  
   */
  createUsersWithListInput(body: User[] ,
    $config?: RequestInit
  ): Promise<unknown> {
    let url = defaults.baseUrl + '/user/createWithList?';

    return fetch(url, {
      method: 'POST',
      body: JSON.stringify(body),
      ...$config,
    }).then((response) => response.json() as Promise<unknown>);
  },

  /**
   * @param username  
   */
  deleteUser(username: string ,
    $config?: RequestInit
  ): Promise<unknown> {
    let url = defaults.baseUrl + '/user/{username}?';
    url = url.replace('{username}', encodeURIComponent("" + username));

    return fetch(url, {
      method: 'DELETE',
      ...$config,
    }).then((response) => response.json() as Promise<unknown>);
  },

  /**
   * @param username  
   */
  getUserByName(username: string ,
    $config?: RequestInit
  ): Promise<User> {
    let url = defaults.baseUrl + '/user/{username}?';
    url = url.replace('{username}', encodeURIComponent("" + username));

    return fetch(url, {
      method: 'GET',
      ...$config,
    }).then((response) => response.json() as Promise<User>);
  },

  /**
   * @param username  
   * @param password  
   */
  loginUser(username: string ,
    password: string ,
    $config?: RequestInit
  ): Promise<string> {
    let url = defaults.baseUrl + '/user/login?';
    if (username !== undefined) {
      url += 'username=' + serializeQueryParam(username) + "&";
    }
    if (password !== undefined) {
      url += 'password=' + serializeQueryParam(password) + "&";
    }
  
    return fetch(url, {
      method: 'GET',
      ...$config,
    }).then((response) => response.json() as Promise<string>);
  },

  /**
   */
  logoutUser($config?: RequestInit
  ): Promise<unknown> {
    let url = defaults.baseUrl + '/user/logout?';

    return fetch(url, {
      method: 'GET',
      ...$config,
    }).then((response) => response.json() as Promise<unknown>);
  },

  /**
   * @param username  
   * @param body  
   */
  updateUser(username: string ,
    body: User ,
    $config?: RequestInit
  ): Promise<unknown> {
    let url = defaults.baseUrl + '/user/{username}?';
    url = url.replace('{username}', encodeURIComponent("" + username));

    return fetch(url, {
      method: 'PUT',
      body: JSON.stringify(body),
      ...$config,
    }).then((response) => response.json() as Promise<unknown>);
  },

};

function serializeQueryParam(obj: any) {
  if (obj === null || obj === undefined) return '';
  if (obj instanceof Date) return encodeURIComponent(obj.toJSON());
  if (typeof obj !== 'object' || Array.isArray(obj)) return encodeURIComponent(obj);
  return Object.keys(obj)
    .reduce((a: any, b) => a.push(encodeURIComponent(b) + '=' + encodeURIComponent(obj[b])) && a, [])
    .join('&');
}

export interface ApiResponse {
  code?: number;
  type?: string;
  message?: string;
}

export interface Category {
  id?: number;
  name?: string;
}

export interface Pet {
  name: string;
  photoUrls: string[];
  id?: number;
  category?: Category;
  tags?: Tag[];

  status?: 'available'|'pending'|'sold';
}

export interface Tag {
  id?: number;
  name?: string;
}

export interface Order {
  id?: number;
  petId?: number;
  quantity?: number;
  shipDate?: Date;

  status?: 'placed'|'approved'|'delivered';
  complete?: boolean;
}

export interface User {
  id?: number;
  username?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  password?: string;
  phone?: string;

  userStatus?: number;
}
