/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file

import ky, { type Options as KyOptions } from 'ky';

export const http = ky.create({
  prefix: '',
});
export const petClient = {
   /**
  * Add a new pet to the store
  * @param body
  */
  addPet(body: Pet ,
    $config?: KyOptions
  ): Promise<Pet> {
    const url = `pet`;

    return http.post(url, {
      json: body,
      ...$config,
    }).json<Pet>();
  },

 /**
  * Deletes a pet
  * @param apiKey (optional) (API name: api_key)
  * @param petId - ID of the pet
  */
  deletePet(apiKey: string | null | undefined,
    petId: number ,
    $config?: KyOptions
  ): Promise<unknown> {
    const url = `pet/${encodeURIComponent(`${petId}`)}`;

    return http.delete(url, {
      headers: {
        'api_key': apiKey,
      },
      ...$config,
    }).json<unknown>();
  },

 /**
  * Finds Pets
  * Find pets using different filters
  * @param queryParams (optional) - Grouped query parameters object (status, name, type, owner, sortBy, order, page, limit, city, registrationDate)
  */
  findPets(queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null,
    $config?: KyOptions
  ): Promise<Pet[]> {
    const url = `pet/find`;

    return http.get(url, {
      searchParams: {
        'status': queryParams?.status as any,
        'name': queryParams?.name as any,
        'type': queryParams?.type as any,
        'owner': queryParams?.owner as any,
        'sortBy': queryParams?.sortBy as any,
        'order': queryParams?.order as any,
        'page': queryParams?.page as any,
        'limit': queryParams?.limit as any,
        'city': queryParams?.city as any,
        'registrationDate': queryParams?.registrationDate as any,
      },
      ...$config,
    }).json<Pet[]>();
  },

 /**
  * Finds Pets by tags
  * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
  * @deprecated
  * @param tags (optional) - Tags to filter by
  */
  findPetsByTags(tags?: string[] | null,
    $config?: KyOptions
  ): Promise<Pet[]> {
    const url = `pet/findByTags`;

    return http.get(url, {
      searchParams: {
        'tags': tags as any,
      },
      ...$config,
    }).json<Pet[]>();
  },

 /**
  * Find pet by ID
  * Returns a single pet
  * @param petId - ID of the pet
  */
  getPetById(petId: number ,
    $config?: KyOptions
  ): Promise<Pet> {
    const url = `pet/${encodeURIComponent(`${petId}`)}`;

    return http.get(url, {
      ...$config,
    }).json<Pet>();
  },

 /**
  * Update an existing pet by Id
  * @param body
  */
  updatePet(body: Pet ,
    $config?: KyOptions
  ): Promise<Pet> {
    const url = `pet`;

    return http.put(url, {
      body: new URLSearchParams(body as any),
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      ...$config,
    }).json<Pet>();
  },

 /**
  * Updates a pet in the store with form data
  * @param petId - ID of the pet
  * @param queryParams (optional) - Grouped query parameters object (name, status)
  */
  updatePetWithForm(petId: number ,
    queryParams?: { name?: string | null; status?: string | null; } | null,
    $config?: KyOptions
  ): Promise<unknown> {
    const url = `pet/${encodeURIComponent(`${petId}`)}`;

    return http.post(url, {
      searchParams: {
        'name': queryParams?.name as any,
        'status': queryParams?.status as any,
      },
      ...$config,
    }).json<unknown>();
  },

 /**
  * uploads an image
  * @param body (optional)
  * @param petId - ID of the pet
  * @param additionalMetadata (optional) - Additional Metadata
  */
  uploadFile(body: File | null | undefined,
    petId: number ,
    additionalMetadata?: string | null,
    $config?: KyOptions
  ): Promise<File> {
    const url = `pet/${encodeURIComponent(`${petId}`)}/uploadImage`;

    return http.post(url, {
      body: body,
      searchParams: {
        'additionalMetadata': additionalMetadata as any,
      },
      ...$config,
    }).blob() as Promise<File>;
  },

};
export const storeClient = {
   /**
  * Delete purchase order by ID
  * For valid response try integer IDs with value &lt; 1000. Anything above 1000 or nonintegers will generate API errors
  * @param orderId - ID of the order that needs to be deleted
  */
  deleteOrder(orderId: number ,
    $config?: KyOptions
  ): Promise<unknown> {
    const url = `store/order/${encodeURIComponent(`${orderId}`)}`;

    return http.delete(url, {
      ...$config,
    }).json<unknown>();
  },

 /**
  * Returns pet inventories by status
  * Returns a map of status codes to quantities
  */
  getInventory($config?: KyOptions
  ): Promise<Record<string, number>> {
    const url = `store/inventory`;

    return http.get(url, {
      ...$config,
    }).json<Record<string, number>>();
  },

 /**
  * Find purchase order by ID
  * For valid response try integer IDs with value &le; 5 or &gt; 10. Other values will generate exceptions.
  * @param orderId - ID of order that needs to be fetched
  */
  getOrderById(orderId: number ,
    $config?: KyOptions
  ): Promise<Order> {
    const url = `store/order/${encodeURIComponent(`${orderId}`)}`;

    return http.get(url, {
      ...$config,
    }).json<Order>();
  },

 /**
  * Place an order for a pet
  * Place a new order in the store
  * @param body (optional)
  */
  placeOrder(body?: Order | null,
    $config?: KyOptions
  ): Promise<Order> {
    const url = `store/order`;

    return http.post(url, {
      json: body,
      ...$config,
    }).json<Order>();
  },

};
export const userClient = {
   /**
  * Create user
  * This can only be done by the logged in user.
  * @param body (optional)
  */
  createUser(body?: User | null,
    $config?: KyOptions
  ): Promise<User> {
    const url = `user`;

    return http.post(url, {
      json: body,
      ...$config,
    }).json<User>();
  },

 /**
  * Creates list of users with given input array
  * @param body (optional)
  */
  createUsersWithListInput(body?: User[] | null,
    $config?: KyOptions
  ): Promise<User> {
    const url = `user/createWithList`;

    return http.post(url, {
      json: body,
      ...$config,
    }).json<User>();
  },

 /**
  * Delete user
  * This can only be done by the logged in user.
  * @param username - The name that needs to be deleted
  */
  deleteUser(username: string ,
    $config?: KyOptions
  ): Promise<unknown> {
    const url = `user/${encodeURIComponent(`${username}`)}`;

    return http.delete(url, {
      ...$config,
    }).json<unknown>();
  },

 /**
  * Get user by user name
  * @param username - The name that needs to be fetched. Use user1 for testing.
  */
  getUserByName(username: string ,
    $config?: KyOptions
  ): Promise<User> {
    const url = `user/${encodeURIComponent(`${username}`)}`;

    return http.get(url, {
      ...$config,
    }).json<User>();
  },

 /**
  * Logs user into the system
  * @param queryParams (optional) - Grouped query parameters object (username, password)
  */
  loginUser(queryParams?: { username?: string | null; password?: string | null; } | null,
    $config?: KyOptions
  ): Promise<string> {
    const url = `user/login`;

    return http.get(url, {
      searchParams: {
        'username': queryParams?.username as any,
        'password': queryParams?.password as any,
      },
      ...$config,
    }).json<string>();
  },

/** Logs out current logged in user session */
  logoutUser($config?: KyOptions
  ): Promise<unknown> {
    const url = `user/logout`;

    return http.get(url, {
      ...$config,
    }).json<unknown>();
  },

 /**
  * Update user
  * This can only be done by the logged in user.
  * @param body (optional)
  * @param username - name that needs to be updated
  */
  updateUser(body: FormData | null | undefined,
    username: string ,
    $config?: KyOptions
  ): Promise<unknown> {
    const url = `user/${encodeURIComponent(`${username}`)}`;

    return http.put(url, {
      body: body,
      ...$config,
    }).json<unknown>();
  },

};

/**
 * Serializes a params object into a query string that is compatible with different REST APIs.
 * Implementation from: https://github.com/suhaotian/xior/blob/main/src/utils.ts
 * Kudos to @suhaotian for the original implementation
 */
export function encodeParams<T = any>(
  params: T,
  parentKey: string | null = null,
  options?: {
    allowDots?: boolean;
    serializeDate?: (value: Date) => string;
    arrayFormat?: 'indices' | 'repeat' | 'brackets';
  }
): string {
  if (params === undefined || params === null) return '';
  const encodedParams: string[] = [];
  const paramsIsArray = Array.isArray(params);
  const { arrayFormat, allowDots, serializeDate } = options || {};

  const getKey = (key: string) => {
    if (allowDots && !paramsIsArray) return `.${key}`;
    if (paramsIsArray) {
      if (arrayFormat === 'brackets') {
        return '[]';
      }
      if (arrayFormat === 'repeat') {
        return '';
      }
    }
    return `[${key}]`;
  };

  for (const key in params) {
    if (Object.prototype.hasOwnProperty.call(params, key)) {
      let value = (params as any)[key];
      if (value !== undefined) {
        const encodedKey = parentKey ? `${parentKey}${getKey(key)}` : (key as string);

        // biome-ignore lint/suspicious/noGlobalIsNan: <explanation>
        if (!isNaN(value) && value instanceof Date) {
          value = serializeDate ? serializeDate(value) : value.toISOString();
        }
        if (typeof value === 'object') {
          // If the value is an object or array, recursively encode its contents
          const result = encodeParams(value, encodedKey, options);
          if (result !== '') encodedParams.push(result);
        } else {
          // Otherwise, encode the key-value pair
          encodedParams.push(`${encodeURIComponent(encodedKey)}=${encodeURIComponent(value)}`);
        }
      }
    }
  }

  return encodedParams.join('&');
}
export interface Order {
  /** @format int64 */
  id?: number;
  /** @format int64 */
  petId?: number;
  /** @format int32 */
  quantity?: number;
  /** @format date-time */
  shipDate?: Date;
  /** Order Status */
  status?: "placed" | "approved" | "delivered";
  complete?: boolean;
}

export type Category = { id?: number;
name?: string; } & Record<string, boolean>;

export type User = { id: number;
username?: string;
firstName?: string;
lastName?: string;
email: string;
password?: string;
phone?: string | null;
userStatus?: number; } | { id: number;
username: string;
firstName?: string;
lastName?: string;
email?: string;
password?: string;
phone?: string | null;
userStatus?: number; };

export interface Tag {
  /** @format int64 */
  id?: number;
  name?: string;
}

export type Pet = { id?: number;
name: string;
category?: Category;
photoUrls: string[] | null;
tags?: Tag[];
status?: "available" | "pending" | "sold"; } & Record<string, Item>;

export type Item = Record<string, Tag>;
