/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file
import { vi } from 'vitest';

import type { PetService, StoreService, UserService } from './api';

export type MockedService<T> = {
  [K in keyof T]: T[K] extends (...args: infer A) => infer R ? (...args: A) => R : T[K];
};

export function createClientMocks() {
  return {
    petClient: {
      addPet: vi.fn<typeof PetService.prototype.addPet>(),
      deletePet: vi.fn<typeof PetService.prototype.deletePet>(),
      findPets: vi.fn<typeof PetService.prototype.findPets>(),
      findPetsByTags: vi.fn<typeof PetService.prototype.findPetsByTags>(),
      getPetById: vi.fn<typeof PetService.prototype.getPetById>(),
      updatePet: vi.fn<typeof PetService.prototype.updatePet>(),
      updatePetWithForm: vi.fn<typeof PetService.prototype.updatePetWithForm>(),
      uploadFile: vi.fn<typeof PetService.prototype.uploadFile>(),
    } satisfies MockedService<PetService>,
    storeClient: {
      deleteOrder: vi.fn<typeof StoreService.prototype.deleteOrder>(),
      getInventory: vi.fn<typeof StoreService.prototype.getInventory>(),
      getOrderById: vi.fn<typeof StoreService.prototype.getOrderById>(),
      placeOrder: vi.fn<typeof StoreService.prototype.placeOrder>(),
    } satisfies MockedService<StoreService>,
    userClient: {
      createUser: vi.fn<typeof UserService.prototype.createUser>(),
      createUsersWithListInput: vi.fn<typeof UserService.prototype.createUsersWithListInput>(),
      deleteUser: vi.fn<typeof UserService.prototype.deleteUser>(),
      getUserByName: vi.fn<typeof UserService.prototype.getUserByName>(),
      loginUser: vi.fn<typeof UserService.prototype.loginUser>(),
      logoutUser: vi.fn<typeof UserService.prototype.logoutUser>(),
      updateUser: vi.fn<typeof UserService.prototype.updateUser>(),
    } satisfies MockedService<UserService>,
  };
}

export type ClientMocks = ReturnType<typeof createClientMocks>;
