/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file

import type { Observable } from "rxjs";
import { Injectable, InjectionToken, inject } from "@angular/core";
import { HttpClient, type HttpContext, type HttpHeaders, type HttpParams } from "@angular/common/http";

export const API_BASE_URL = new InjectionToken<string>("API_BASE_URL");

export interface HttpConfig {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?: HttpParams | Record<string, string | number | boolean | (string | number | boolean)[]>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  transferCache?: boolean | { includeHeaders?: string[] };
}

function paramsSerializer(params: any) {
  return encodeParams(params, null, {
    allowDots: true,
    arrayFormat: 'repeat',
  });
}

@Injectable({
  providedIn: 'root'
})
export class PetService {
  private http = inject(HttpClient);
  private baseUrl = inject(API_BASE_URL, { optional: true }) ?? '';

   /**
  * Add a new pet to the store
  * @param body
  */
  addPet(
    body: Pet ,
    config?: HttpConfig
  ): Observable<Pet> {
    const url = `/pet`;
    return this.http.post<Pet>(this.baseUrl + url, body, config);
  }

 /**
  * Deletes a pet
  * @param apiKey (optional) (API name: api_key)
  * @param petId - ID of the pet
  */
  deletePet(
    apiKey: string | null | undefined,
    petId: number ,
    config?: HttpConfig
  ): Observable<unknown> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;
    if (apiKey) {
      config = { ...config, headers: { ...config?.headers, 'api_key': apiKey } };
    }
    return this.http.delete<unknown>(this.baseUrl + url, config);
  }

 /**
  * Finds Pets
  * Find pets using different filters
  * @param queryParams (optional) - Grouped query parameters object (status, name, type, owner, sortBy, order, page, limit, city, registrationDate)
  */
  findPets(
    queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null,
    config?: HttpConfig
  ): Observable<Pet[]> {
    const params = paramsSerializer({
      'status': queryParams?.status,
      'name': queryParams?.name,
      'type': queryParams?.type,
      'owner': queryParams?.owner,
      'sortBy': queryParams?.sortBy,
      'order': queryParams?.order,
      'page': queryParams?.page,
      'limit': queryParams?.limit,
      'city': queryParams?.city,
      'registrationDate': queryParams?.registrationDate,
    });
    const url = `/pet/find${params ? '?' + params : ''}`;
    return this.http.get<Pet[]>(this.baseUrl + url, config);
  }

 /**
  * Finds Pets by tags
  * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
  * @deprecated
  * @param tags (optional) - Tags to filter by
  */
  findPetsByTags(
    tags?: string[] | null,
    config?: HttpConfig
  ): Observable<Pet[]> {
    const params = paramsSerializer({
      'tags': tags,
    });
    const url = `/pet/findByTags${params ? '?' + params : ''}`;
    return this.http.get<Pet[]>(this.baseUrl + url, config);
  }

 /**
  * Find pet by ID
  * Returns a single pet
  * @param petId - ID of the pet
  */
  getPetById(
    petId: number ,
    config?: HttpConfig
  ): Observable<Pet> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;
    return this.http.get<Pet>(this.baseUrl + url, config);
  }

 /**
  * Update an existing pet by Id
  * @param body
  */
  updatePet(
    body: Pet ,
    config?: HttpConfig
  ): Observable<Pet> {
    const url = `/pet`;
    config = { ...config, headers: { ...config?.headers, 'Content-Type': 'application/x-www-form-urlencoded' } };
    return this.http.put<Pet>(this.baseUrl + url, new URLSearchParams(body as any), config);
  }

 /**
  * Updates a pet in the store with form data
  * @param petId - ID of the pet
  * @param queryParams (optional) - Grouped query parameters object (name, status)
  */
  updatePetWithForm(
    petId: number ,
    queryParams?: { name?: string | null; status?: string | null; } | null,
    config?: HttpConfig
  ): Observable<unknown> {
    const params = paramsSerializer({
      'name': queryParams?.name,
      'status': queryParams?.status,
    });
    const url = `/pet/${encodeURIComponent(`${petId}`)}${params ? '?' + params : ''}`;
    return this.http.post<unknown>(this.baseUrl + url, null, config);
  }

 /**
  * uploads an image
  * @param body (optional)
  * @param petId - ID of the pet
  * @param additionalMetadata (optional) - Additional Metadata
  */
  uploadFile(
    body: File | null | undefined,
    petId: number ,
    additionalMetadata?: string | null,
    config?: HttpConfig
  ): Observable<File> {
    const params = paramsSerializer({
      'additionalMetadata': additionalMetadata,
    });
    const url = `/pet/${encodeURIComponent(`${petId}`)}/uploadImage${params ? '?' + params : ''}`;
    return this.http.post<File>(this.baseUrl + url, body, config);
  }

}

@Injectable({
  providedIn: 'root'
})
export class StoreService {
  private http = inject(HttpClient);
  private baseUrl = inject(API_BASE_URL, { optional: true }) ?? '';

   /**
  * Delete purchase order by ID
  * For valid response try integer IDs with value &lt; 1000. Anything above 1000 or nonintegers will generate API errors
  * @param orderId - ID of the order that needs to be deleted
  */
  deleteOrder(
    orderId: number ,
    config?: HttpConfig
  ): Observable<unknown> {
    const url = `/store/order/${encodeURIComponent(`${orderId}`)}`;
    return this.http.delete<unknown>(this.baseUrl + url, config);
  }

 /**
  * Returns pet inventories by status
  * Returns a map of status codes to quantities
  */
  getInventory(
    config?: HttpConfig
  ): Observable<Record<string, number>> {
    const url = `/store/inventory`;
    return this.http.get<Record<string, number>>(this.baseUrl + url, config);
  }

 /**
  * Find purchase order by ID
  * For valid response try integer IDs with value &le; 5 or &gt; 10. Other values will generate exceptions.
  * @param orderId - ID of order that needs to be fetched
  */
  getOrderById(
    orderId: number ,
    config?: HttpConfig
  ): Observable<Order> {
    const url = `/store/order/${encodeURIComponent(`${orderId}`)}`;
    return this.http.get<Order>(this.baseUrl + url, config);
  }

 /**
  * Place an order for a pet
  * Place a new order in the store
  * @param body (optional)
  */
  placeOrder(
    body?: Order | null,
    config?: HttpConfig
  ): Observable<Order> {
    const url = `/store/order`;
    return this.http.post<Order>(this.baseUrl + url, body, config);
  }

}

@Injectable({
  providedIn: 'root'
})
export class UserService {
  private http = inject(HttpClient);
  private baseUrl = inject(API_BASE_URL, { optional: true }) ?? '';

   /**
  * Create user
  * This can only be done by the logged in user.
  * @param body (optional)
  */
  createUser(
    body?: User | null,
    config?: HttpConfig
  ): Observable<User> {
    const url = `/user`;
    return this.http.post<User>(this.baseUrl + url, body, config);
  }

 /**
  * Creates list of users with given input array
  * @param body (optional)
  */
  createUsersWithListInput(
    body?: User[] | null,
    config?: HttpConfig
  ): Observable<User> {
    const url = `/user/createWithList`;
    return this.http.post<User>(this.baseUrl + url, body, config);
  }

 /**
  * Delete user
  * This can only be done by the logged in user.
  * @param username - The name that needs to be deleted
  */
  deleteUser(
    username: string ,
    config?: HttpConfig
  ): Observable<unknown> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;
    return this.http.delete<unknown>(this.baseUrl + url, config);
  }

 /**
  * Get user by user name
  * @param username - The name that needs to be fetched. Use user1 for testing.
  */
  getUserByName(
    username: string ,
    config?: HttpConfig
  ): Observable<User> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;
    return this.http.get<User>(this.baseUrl + url, config);
  }

 /**
  * Logs user into the system
  * @param queryParams (optional) - Grouped query parameters object (username, password)
  */
  loginUser(
    queryParams?: { username?: string | null; password?: string | null; } | null,
    config?: HttpConfig
  ): Observable<string> {
    const params = paramsSerializer({
      'username': queryParams?.username,
      'password': queryParams?.password,
    });
    const url = `/user/login${params ? '?' + params : ''}`;
    return this.http.get<string>(this.baseUrl + url, config);
  }

/** Logs out current logged in user session */
  logoutUser(
    config?: HttpConfig
  ): Observable<unknown> {
    const url = `/user/logout`;
    return this.http.get<unknown>(this.baseUrl + url, config);
  }

 /**
  * Update user
  * This can only be done by the logged in user.
  * @param body (optional)
  * @param username - name that needs to be updated
  */
  updateUser(
    body: FormData | null | undefined,
    username: string ,
    config?: HttpConfig
  ): Observable<unknown> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;
    return this.http.put<unknown>(this.baseUrl + url, body, config);
  }

}


/**
 * Serializes a params object into a query string that is compatible with different REST APIs.
 * Implementation from: https://github.com/suhaotian/xior/blob/main/src/utils.ts
 * Kudos to @suhaotian for the original implementation
 */
function encodeParams<T = any>(
  params: T,
  parentKey: string | null = null,
  options?: {
    allowDots?: boolean;
    serializeDate?: (value: Date) => string;
    arrayFormat?: 'indices' | 'repeat' | 'brackets';
  }
): string {
  if (params === undefined || params === null) return '';
  const encodedParams: string[] = [];
  const paramsIsArray = Array.isArray(params);
  const { arrayFormat, allowDots, serializeDate } = options || {};

  const getKey = (key: string) => {
    if (allowDots && !paramsIsArray) return `.${key}`;
    if (paramsIsArray) {
      if (arrayFormat === 'brackets') {
        return '[]';
      }
      if (arrayFormat === 'repeat') {
        return '';
      }
    }
    return `[${key}]`;
  };

  for (const key in params) {
    if (Object.prototype.hasOwnProperty.call(params, key)) {
      let value = (params as any)[key];
      if (value !== undefined) {
        const encodedKey = parentKey ? `${parentKey}${getKey(key)}` : (key as string);

        // biome-ignore lint/suspicious/noGlobalIsNan: <explanation>
        if (!isNaN(value) && value instanceof Date) {
          value = serializeDate ? serializeDate(value) : value.toISOString();
        }
        if (typeof value === 'object') {
          // If the value is an object or array, recursively encode its contents
          const result = encodeParams(value, encodedKey, options);
          if (result !== '') encodedParams.push(result);
        } else {
          // Otherwise, encode the key-value pair
          encodedParams.push(`${encodeURIComponent(encodedKey)}=${encodeURIComponent(value)}`);
        }
      }
    }
  }

  return encodedParams.join('&');
}

export interface Order {
  /** @format int64 */
  id?: number;
  /** @format int64 */
  petId?: number;
  /** @format int32 */
  quantity?: number;
  /** @format date-time */
  shipDate?: Date;
  /** Order Status */
  status?: "placed" | "approved" | "delivered";
  complete?: boolean;
}

export type Category = { id?: number;
name?: string; } & Record<string, boolean>;

export type User = { id: number;
username?: string;
firstName?: string;
lastName?: string;
email: string;
password?: string;
phone?: string | null;
userStatus?: number; } | { id: number;
username: string;
firstName?: string;
lastName?: string;
email?: string;
password?: string;
phone?: string | null;
userStatus?: number; };

export interface Tag {
  /** @format int64 */
  id?: number;
  name?: string;
}

export type Pet = { id?: number;
name: string;
category?: Category;
photoUrls: string[] | null;
tags?: Tag[];
status?: "available" | "pending" | "sold"; } & Record<string, Item>;

export type Item = Record<string, Tag>;
