/* istanbul ignore file -- auto-generated code */
/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file

export type Order = {
  /** @format int64 */
  id?: number;
  /** @format int64 */
  petId?: number;
  /** @format int32 */
  quantity?: number;
  /** @format date-time */
  shipDate?: Date;
  /** Order Status */
  status?: "placed" | "approved" | "delivered";
  complete?: boolean;
};

export type Customer = {
  /** @format int64 */
  id?: number;
  username?: string;
  address?: Address[] | null;
};

export type Address = {
  street?: string;
  city?: string;
  state?: string;
  zip?: string;
};

export type Category = { id?: number;
name?: string; } & { [key: string]: boolean };

export type User = { id: number;
username?: string;
firstName?: string;
lastName?: string;
email: string;
password?: string;
phone?: string | null;
userStatus?: number; } | { id: number;
username: string;
firstName?: string;
lastName?: string;
email?: string;
password?: string;
phone?: string | null;
userStatus?: number; };

export type Tag = {
  /** @format int64 */
  id?: number;
  name?: string;
};

export type Pet = { id?: number;
name: string;
category?: Category;
photoUrls: string[] | null;
tags?: Tag[];
status?: "available" | "pending" | "sold"; } & { [key: string]: Item };

export type ApiResponse = {
  /** @format int32 */
  code?: number;
  type?: string;
  message?: string;
};

export type Item = { [key: string]: Tag };
