/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file

import useSWR, { type SWRConfiguration, type Key } from 'swr';
import useSWRMutation, { type SWRMutationConfiguration } from 'swr/mutation';

interface SwrConfig extends SWRConfiguration {
  /* Custom key for SWR. You don't have to worry about this as by default it's the URL. You can use standard SWR Key here if you need more flexibility. */
  key?: Key;
}
import ky, { type Options as KyOptions } from 'ky';

export const http = ky.create({
  prefix: '',
});
export const petClient = {
   /**
  * Add a new pet to the store
  * @param body
  */
  addPet(body: Pet ,
    $config?: KyOptions
  ): Promise<Pet> {
    const url = `pet`;

    return http.post(url, {
      json: body,
      ...$config,
    }).json<Pet>();
  },

   /**
  * Deletes a pet
  * @param apiKey (optional) (API name: api_key)
  * @param petId - ID of the pet
  */
  deletePet(apiKey: string | null | undefined,
    petId: number ,
    $config?: KyOptions
  ): Promise<unknown> {
    const url = `pet/${encodeURIComponent(`${petId}`)}`;

    return http.delete(url, {
      headers: {
        'api_key': apiKey,
      },
      ...$config,
    }).json<unknown>();
  },

   /**
  * Finds Pets
  * Find pets using different filters
  * @param queryParams (optional) - Grouped query parameters object (status, name, type, owner, sortBy, order, page, limit, city, registrationDate)
  */
  findPets(queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null,
    $config?: KyOptions
  ): Promise<Pet[]> {
    const url = `pet/find`;

    return http.get(url, {
      searchParams: encodeParams({
        'status': queryParams?.status,
        'name': queryParams?.name,
        'type': queryParams?.type,
        'owner': queryParams?.owner,
        'sortBy': queryParams?.sortBy,
        'order': queryParams?.order,
        'page': queryParams?.page,
        'limit': queryParams?.limit,
        'city': queryParams?.city,
        'registrationDate': queryParams?.registrationDate,
      }),
      ...$config,
    }).json<Pet[]>();
  },

   /**
  * Finds Pets by tags
  * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
  * @deprecated
  * @param tags (optional) - Tags to filter by
  */
  findPetsByTags(tags?: string[] | null,
    $config?: KyOptions
  ): Promise<Pet[]> {
    const url = `pet/findByTags`;

    return http.get(url, {
      searchParams: encodeParams({
        'tags': tags,
      }),
      ...$config,
    }).json<Pet[]>();
  },

   /**
  * Find pet by ID
  * Returns a single pet
  * @param petId - ID of the pet
  */
  getPetById(petId: number ,
    $config?: KyOptions
  ): Promise<Pet> {
    const url = `pet/${encodeURIComponent(`${petId}`)}`;

    return http.get(url, {
      ...$config,
    }).json<Pet>();
  },

   /**
  * Update an existing pet by Id
  * @param body
  */
  updatePet(body: Pet ,
    $config?: KyOptions
  ): Promise<Pet> {
    const url = `pet`;

    return http.put(url, {
      body: new URLSearchParams(body as any),
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      ...$config,
    }).json<Pet>();
  },

   /**
  * Updates a pet in the store with form data
  * @param petId - ID of the pet
  * @param queryParams (optional) - Grouped query parameters object (name, status)
  */
  updatePetWithForm(petId: number ,
    queryParams?: { name?: string | null; status?: string | null; } | null,
    $config?: KyOptions
  ): Promise<unknown> {
    const url = `pet/${encodeURIComponent(`${petId}`)}`;

    return http.post(url, {
      searchParams: encodeParams({
        'name': queryParams?.name,
        'status': queryParams?.status,
      }),
      ...$config,
    }).json<unknown>();
  },

   /**
  * uploads an image
  * @param body (optional)
  * @param petId - ID of the pet
  * @param additionalMetadata (optional) - Additional Metadata
  */
  uploadFile(body: File | null | undefined,
    petId: number ,
    additionalMetadata?: string | null,
    $config?: KyOptions
  ): Promise<File> {
    const url = `pet/${encodeURIComponent(`${petId}`)}/uploadImage`;

    return http.post(url, {
      body: body,
      searchParams: encodeParams({
        'additionalMetadata': additionalMetadata,
      }),
      ...$config,
    }).blob() as Promise<File>;
  },

  };


export const pet = {
  queries: {
   /**
    * Finds Pets
    * Find pets using different filters
    * @param queryParams (optional) - Grouped query parameters object (status, name, type, owner, sortBy, order, page, limit, city, registrationDate)
    */
    useFindPets(
      queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: KyOptions    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? pet.queryKeys.findPets(queryParams, );

      const { data, error, isLoading, mutate } = useSWR<Pet[]>(
        cacheUrl,
        () => petClient.findPets(queryParams, $httpConfig),
        config
      );

      return { data, isLoading, error, mutate };
    },

   /**
    * Finds Pets by tags
    * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
    * @deprecated
    * @param tags (optional) - Tags to filter by
    */
    useFindPetsByTags(
      tags?: string[] | null,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: KyOptions    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? pet.queryKeys.findPetsByTags(tags, );

      const { data, error, isLoading, mutate } = useSWR<Pet[]>(
        cacheUrl,
        () => petClient.findPetsByTags(tags, $httpConfig),
        config
      );

      return { data, isLoading, error, mutate };
    },

   /**
    * Find pet by ID
    * Returns a single pet
    * @param petId - ID of the pet
    */
    usePetById(
      petId: number,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: KyOptions    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? pet.queryKeys.petById(petId, );

      const { data, error, isLoading, mutate } = useSWR<Pet>(
        cacheUrl,
        () => petClient.getPetById(petId, $httpConfig),
        config
      );

      return { data, isLoading, error, mutate };
    },

  },

  mutations: {
   /**
    * Add a new pet to the store
    * @param body
    */
    useAddPet(
      $config?: SWRMutationConfiguration<Pet, Error, string, { body: Pet }>,
      $httpConfig?: KyOptions    ) {
      return useSWRMutation<Pet, Error, string, { body: Pet }>(
        '/pet',
        (_key: string, { arg }: { arg: { body: Pet } }) =>
          petClient.addPet(arg.body, $httpConfig),
        $config
      );
    },

   /**
    * Deletes a pet
    * @param apiKey (optional) (API name: api_key)
    * @param petId - ID of the pet
    */
    useDeletePet(
      $config?: SWRMutationConfiguration<unknown, Error, string, { apiKey: string | null; petId: number }>,
      $httpConfig?: KyOptions    ) {
      return useSWRMutation<unknown, Error, string, { apiKey: string | null; petId: number }>(
        '/pet/*',
        (_key: string, { arg }: { arg: { apiKey: string | null; petId: number } }) =>
          petClient.deletePet(arg.apiKey, arg.petId, $httpConfig),
        $config
      );
    },

   /**
    * Update an existing pet by Id
    * @param body
    */
    useUpdatePet(
      $config?: SWRMutationConfiguration<Pet, Error, string, { body: Pet }>,
      $httpConfig?: KyOptions    ) {
      return useSWRMutation<Pet, Error, string, { body: Pet }>(
        '/pet',
        (_key: string, { arg }: { arg: { body: Pet } }) =>
          petClient.updatePet(arg.body, $httpConfig),
        $config
      );
    },

   /**
    * Updates a pet in the store with form data
    * @param petId - ID of the pet
    * @param queryParams (optional) - Grouped query parameters object (name, status)
    */
    useUpdatePetWithForm(
      $config?: SWRMutationConfiguration<unknown, Error, string, { petId: number; queryParams?: { name?: string | null; status?: string | null; } | null }>,
      $httpConfig?: KyOptions    ) {
      return useSWRMutation<unknown, Error, string, { petId: number; queryParams?: { name?: string | null; status?: string | null; } | null }>(
        '/pet/*',
        (_key: string, { arg }: { arg: { petId: number; queryParams?: { name?: string | null; status?: string | null; } | null } }) =>
          petClient.updatePetWithForm(arg.petId, arg.queryParams, $httpConfig),
        $config
      );
    },

   /**
    * uploads an image
    * @param body (optional)
    * @param petId - ID of the pet
    * @param additionalMetadata (optional) - Additional Metadata
    */
    useUploadFile(
      $config?: SWRMutationConfiguration<File, Error, string, { body: File | null; petId: number; additionalMetadata?: string | null }>,
      $httpConfig?: KyOptions    ) {
      return useSWRMutation<File, Error, string, { body: File | null; petId: number; additionalMetadata?: string | null }>(
        '/pet/*/uploadImage',
        (_key: string, { arg }: { arg: { body: File | null; petId: number; additionalMetadata?: string | null } }) =>
          petClient.uploadFile(arg.body, arg.petId, arg.additionalMetadata, $httpConfig),
        $config
      );
    },

  },

  queryKeys: {
    findPets: (queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null, ) => `/pet/find?${encodeParams({'status': queryParams?.status, 'name': queryParams?.name, 'type': queryParams?.type, 'owner': queryParams?.owner, 'sortBy': queryParams?.sortBy, 'order': queryParams?.order, 'page': queryParams?.page, 'limit': queryParams?.limit, 'city': queryParams?.city, 'registrationDate': queryParams?.registrationDate, })}`,
    findPetsByTags: (tags?: string[] | null, ) => `/pet/findByTags?${encodeParams({'tags': tags, })}`,
    petById: (petId: number, ) => `/pet/${encodeURIComponent(`${petId}`)}`,
  },
};
export const storeClient = {
   /**
  * Delete purchase order by ID
  * For valid response try integer IDs with value &lt; 1000. Anything above 1000 or nonintegers will generate API errors
  * @param orderId - ID of the order that needs to be deleted
  */
  deleteOrder(orderId: number ,
    $config?: KyOptions
  ): Promise<unknown> {
    const url = `store/order/${encodeURIComponent(`${orderId}`)}`;

    return http.delete(url, {
      ...$config,
    }).json<unknown>();
  },

   /**
  * Returns pet inventories by status
  * Returns a map of status codes to quantities
  */
  getInventory($config?: KyOptions
  ): Promise<Record<string, number>> {
    const url = `store/inventory`;

    return http.get(url, {
      ...$config,
    }).json<Record<string, number>>();
  },

   /**
  * Find purchase order by ID
  * For valid response try integer IDs with value &le; 5 or &gt; 10. Other values will generate exceptions.
  * @param orderId - ID of order that needs to be fetched
  */
  getOrderById(orderId: number ,
    $config?: KyOptions
  ): Promise<Order> {
    const url = `store/order/${encodeURIComponent(`${orderId}`)}`;

    return http.get(url, {
      ...$config,
    }).json<Order>();
  },

   /**
  * Place an order for a pet
  * Place a new order in the store
  * @param body (optional)
  */
  placeOrder(body?: Order | null,
    $config?: KyOptions
  ): Promise<Order> {
    const url = `store/order`;

    return http.post(url, {
      json: body,
      ...$config,
    }).json<Order>();
  },

  };


export const store = {
  queries: {
   /**
    * Returns pet inventories by status
    * Returns a map of status codes to quantities
    */
    useInventory(
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: KyOptions    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? store.queryKeys.inventory();

      const { data, error, isLoading, mutate } = useSWR<Record<string, number>>(
        cacheUrl,
        () => storeClient.getInventory($httpConfig),
        config
      );

      return { data, isLoading, error, mutate };
    },

   /**
    * Find purchase order by ID
    * For valid response try integer IDs with value &le; 5 or &gt; 10. Other values will generate exceptions.
    * @param orderId - ID of order that needs to be fetched
    */
    useOrderById(
      orderId: number,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: KyOptions    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? store.queryKeys.orderById(orderId, );

      const { data, error, isLoading, mutate } = useSWR<Order>(
        cacheUrl,
        () => storeClient.getOrderById(orderId, $httpConfig),
        config
      );

      return { data, isLoading, error, mutate };
    },

  },

  mutations: {
   /**
    * Delete purchase order by ID
    * For valid response try integer IDs with value &lt; 1000. Anything above 1000 or nonintegers will generate API errors
    * @param orderId - ID of the order that needs to be deleted
    */
    useDeleteOrder(
      $config?: SWRMutationConfiguration<unknown, Error, string, { orderId: number }>,
      $httpConfig?: KyOptions    ) {
      return useSWRMutation<unknown, Error, string, { orderId: number }>(
        '/store/order/*',
        (_key: string, { arg }: { arg: { orderId: number } }) =>
          storeClient.deleteOrder(arg.orderId, $httpConfig),
        $config
      );
    },

   /**
    * Place an order for a pet
    * Place a new order in the store
    * @param body (optional)
    */
    usePlaceOrder(
      $config?: SWRMutationConfiguration<Order, Error, string, { body?: Order | null }>,
      $httpConfig?: KyOptions    ) {
      return useSWRMutation<Order, Error, string, { body?: Order | null }>(
        '/store/order',
        (_key: string, { arg }: { arg: { body?: Order | null } }) =>
          storeClient.placeOrder(arg.body, $httpConfig),
        $config
      );
    },

  },

  queryKeys: {
    inventory: () => `/store/inventory`,
    orderById: (orderId: number, ) => `/store/order/${encodeURIComponent(`${orderId}`)}`,
  },
};
export const userClient = {
   /**
  * Create user
  * This can only be done by the logged in user.
  * @param body (optional)
  */
  createUser(body?: User | null,
    $config?: KyOptions
  ): Promise<User> {
    const url = `user`;

    return http.post(url, {
      json: body,
      ...$config,
    }).json<User>();
  },

   /**
  * Creates list of users with given input array
  * @param body (optional)
  */
  createUsersWithListInput(body?: User[] | null,
    $config?: KyOptions
  ): Promise<User> {
    const url = `user/createWithList`;

    return http.post(url, {
      json: body,
      ...$config,
    }).json<User>();
  },

   /**
  * Delete user
  * This can only be done by the logged in user.
  * @param username - The name that needs to be deleted
  */
  deleteUser(username: string ,
    $config?: KyOptions
  ): Promise<unknown> {
    const url = `user/${encodeURIComponent(`${username}`)}`;

    return http.delete(url, {
      ...$config,
    }).json<unknown>();
  },

   /**
  * Get user by user name
  * @param username - The name that needs to be fetched. Use user1 for testing.
  */
  getUserByName(username: string ,
    $config?: KyOptions
  ): Promise<User> {
    const url = `user/${encodeURIComponent(`${username}`)}`;

    return http.get(url, {
      ...$config,
    }).json<User>();
  },

   /**
  * Logs user into the system
  * @param queryParams (optional) - Grouped query parameters object (username, password)
  */
  loginUser(queryParams?: { username?: string | null; password?: string | null; } | null,
    $config?: KyOptions
  ): Promise<string> {
    const url = `user/login`;

    return http.get(url, {
      searchParams: encodeParams({
        'username': queryParams?.username,
        'password': queryParams?.password,
      }),
      ...$config,
    }).json<string>();
  },

  /** Logs out current logged in user session */
  logoutUser($config?: KyOptions
  ): Promise<unknown> {
    const url = `user/logout`;

    return http.get(url, {
      ...$config,
    }).json<unknown>();
  },

   /**
  * Update user
  * This can only be done by the logged in user.
  * @param body (optional)
  * @param username - name that needs to be updated
  */
  updateUser(body: FormData | null | undefined,
    username: string ,
    $config?: KyOptions
  ): Promise<unknown> {
    const url = `user/${encodeURIComponent(`${username}`)}`;

    return http.put(url, {
      body: body,
      ...$config,
    }).json<unknown>();
  },

  };


export const user = {
  queries: {
   /**
    * Get user by user name
    * @param username - The name that needs to be fetched. Use user1 for testing.
    */
    useUserByName(
      username: string,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: KyOptions    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? user.queryKeys.userByName(username, );

      const { data, error, isLoading, mutate } = useSWR<User>(
        cacheUrl,
        () => userClient.getUserByName(username, $httpConfig),
        config
      );

      return { data, isLoading, error, mutate };
    },

   /**
    * Logs user into the system
    * @param queryParams (optional) - Grouped query parameters object (username, password)
    */
    useLoginUser(
      queryParams?: { username?: string | null; password?: string | null; } | null,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: KyOptions    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? user.queryKeys.loginUser(queryParams, );

      const { data, error, isLoading, mutate } = useSWR<string>(
        cacheUrl,
        () => userClient.loginUser(queryParams, $httpConfig),
        config
      );

      return { data, isLoading, error, mutate };
    },

  /** Logs out current logged in user session */
    useLogoutUser(
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: KyOptions    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? user.queryKeys.logoutUser();

      const { data, error, isLoading, mutate } = useSWR<unknown>(
        cacheUrl,
        () => userClient.logoutUser($httpConfig),
        config
      );

      return { data, isLoading, error, mutate };
    },

  },

  mutations: {
   /**
    * Create user
    * This can only be done by the logged in user.
    * @param body (optional)
    */
    useCreateUser(
      $config?: SWRMutationConfiguration<User, Error, string, { body?: User | null }>,
      $httpConfig?: KyOptions    ) {
      return useSWRMutation<User, Error, string, { body?: User | null }>(
        '/user',
        (_key: string, { arg }: { arg: { body?: User | null } }) =>
          userClient.createUser(arg.body, $httpConfig),
        $config
      );
    },

   /**
    * Creates list of users with given input array
    * @param body (optional)
    */
    useCreateUsersWithListInput(
      $config?: SWRMutationConfiguration<User, Error, string, { body?: User[] | null }>,
      $httpConfig?: KyOptions    ) {
      return useSWRMutation<User, Error, string, { body?: User[] | null }>(
        '/user/createWithList',
        (_key: string, { arg }: { arg: { body?: User[] | null } }) =>
          userClient.createUsersWithListInput(arg.body, $httpConfig),
        $config
      );
    },

   /**
    * Delete user
    * This can only be done by the logged in user.
    * @param username - The name that needs to be deleted
    */
    useDeleteUser(
      $config?: SWRMutationConfiguration<unknown, Error, string, { username: string }>,
      $httpConfig?: KyOptions    ) {
      return useSWRMutation<unknown, Error, string, { username: string }>(
        '/user/*',
        (_key: string, { arg }: { arg: { username: string } }) =>
          userClient.deleteUser(arg.username, $httpConfig),
        $config
      );
    },

   /**
    * Update user
    * This can only be done by the logged in user.
    * @param body (optional)
    * @param username - name that needs to be updated
    */
    useUpdateUser(
      $config?: SWRMutationConfiguration<unknown, Error, string, { body: FormData | null; username: string }>,
      $httpConfig?: KyOptions    ) {
      return useSWRMutation<unknown, Error, string, { body: FormData | null; username: string }>(
        '/user/*',
        (_key: string, { arg }: { arg: { body: FormData | null; username: string } }) =>
          userClient.updateUser(arg.body, arg.username, $httpConfig),
        $config
      );
    },

  },

  queryKeys: {
    userByName: (username: string, ) => `/user/${encodeURIComponent(`${username}`)}`,
    loginUser: (queryParams?: { username?: string | null; password?: string | null; } | null, ) => `/user/login?${encodeParams({'username': queryParams?.username, 'password': queryParams?.password, })}`,
    logoutUser: () => `/user/logout`,
  },
};

/**
 * Serializes a params object into a query string that is compatible with different REST APIs.
 * Implementation from: https://github.com/suhaotian/xior/blob/main/src/utils.ts
 * Kudos to @suhaotian for the original implementation
 */
function _encodeParams<T = any>(
  params: T,
  parentKey: string | null = null,
  options?: {
    allowDots?: boolean;
    serializeDate?: (value: Date) => string;
    arrayFormat?: 'indices' | 'repeat' | 'brackets';
  }
): string {
  if (params === undefined || params === null) return '';
  const encodedParams: string[] = [];
  const paramsIsArray = Array.isArray(params);
  const { arrayFormat, allowDots, serializeDate } = options || {};

  const getKey = (key: string) => {
    if (allowDots && !paramsIsArray) return `.${key}`;
    if (paramsIsArray) {
      if (arrayFormat === 'brackets') {
        return '[]';
      }
      if (arrayFormat === 'repeat') {
        return '';
      }
    }
    return `[${key}]`;
  };

  for (const key in params) {
    if (Object.prototype.hasOwnProperty.call(params, key)) {
      let value = (params as any)[key];
      if (value !== undefined) {
        const encodedKey = parentKey ? `${parentKey}${getKey(key)}` : (key as string);

        // biome-ignore lint/suspicious/noGlobalIsNan: <explanation>
        if (!isNaN(value) && value instanceof Date) {
          value = serializeDate ? serializeDate(value) : value.toISOString();
        }
        if (typeof value === 'object') {
          // If the value is an object or array, recursively encode its contents
          const result = _encodeParams(value, encodedKey, options);
          if (result !== '') encodedParams.push(result);
        } else {
          // Otherwise, encode the key-value pair
          encodedParams.push(`${encodeURIComponent(encodedKey)}=${encodeURIComponent(value)}`);
        }
      }
    }
  }

  return encodedParams.join('&');
}

/** Serializes a params object into a query string. Options override the generated defaults (allowDots, arrayFormat). */
export function encodeParams<T = any>(
  params: T,
  parentKey: string | null = null,
  options?: {
    allowDots?: boolean;
    serializeDate?: (value: Date) => string;
    arrayFormat?: 'indices' | 'repeat' | 'brackets';
  }
): string {
  return _encodeParams(params, parentKey, {
    allowDots: true,
    arrayFormat: 'repeat',
    ...options,
  });
}
export interface Order {
  /** @format int64 */
  id?: number;
  /** @format int64 */
  petId?: number;
  /** @format int32 */
  quantity?: number;
  /** @format date-time */
  shipDate?: Date;
  /** Order Status */
  status?: "placed" | "approved" | "delivered";
  complete?: boolean;
}

export type Category = { id?: number;
name?: string; } & Record<string, boolean>;

export type User = { id: number;
username?: string;
firstName?: string;
lastName?: string;
email: string;
password?: string;
phone?: string | null;
userStatus?: number; } | { id: number;
username: string;
firstName?: string;
lastName?: string;
email?: string;
password?: string;
phone?: string | null;
userStatus?: number; };

export interface Tag {
  /** @format int64 */
  id?: number;
  name?: string;
}

export type Pet = { id?: number;
name: string;
category?: Category;
photoUrls: string[] | null;
tags?: Tag[];
status?: "available" | "pending" | "sold"; } & Record<string, Item>;

export type Item = Record<string, Tag>;
