/* istanbul ignore file -- auto-generated test helper */
/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file
import { jest } from '@jest/globals';

import * as realApi from './api';

// ─── SWR mock helpers ────────────────────────────────────────────────────────

/** Augments a spy with a `mockSWR` shorthand for useSWR query hooks. */
function withMockSWR<T extends ReturnType<typeof jest.fn>>(spy: T) {
  return Object.assign(spy, {
    mockSWR({ data, isLoading, error }: { data?: unknown; isLoading?: boolean; error?: Error }) {
      spy.mockReturnValue({ data, isLoading: isLoading ?? false, error: error ?? null, mutate: jest.fn() });
    },
  });
}

/** Augments a spy with a `mockSWRMutation` shorthand for useSWRMutation hooks. */
function withMockSWRMutation<T extends ReturnType<typeof jest.fn>>(spy: T) {
  return Object.assign(spy, {
    mockSWRMutation({ data, isMutating, error }: { data?: unknown; isMutating?: boolean; error?: Error }) {
      spy.mockReturnValue({ trigger: jest.fn(), isMutating: isMutating ?? false, error: error ?? null, data });
    },
  });
}

export const petClient = {
  addPet: jest.fn(),
  deletePet: jest.fn(),
  findPets: jest.fn(),
  findPetsByTags: jest.fn(),
  getPetById: jest.fn(),
  updatePet: jest.fn(),
  updatePetWithForm: jest.fn(),
  uploadFile: jest.fn(),
};

export const pet = {
  queries: {
    useFindPets: withMockSWR(jest.fn()),
    useFindPetsByTags: withMockSWR(jest.fn()),
    usePetById: withMockSWR(jest.fn()),
  },

  mutations: {
    useAddPet: withMockSWRMutation(jest.fn()),
    useDeletePet: withMockSWRMutation(jest.fn()),
    useUpdatePet: withMockSWRMutation(jest.fn()),
    useUpdatePetWithForm: withMockSWRMutation(jest.fn()),
    useUploadFile: withMockSWRMutation(jest.fn()),
  },

  // queryKeys are pure functions — no mocking needed
  queryKeys: realApi.pet.queryKeys,
};

export const storeClient = {
  deleteOrder: jest.fn(),
  getInventory: jest.fn(),
  getOrderById: jest.fn(),
  placeOrder: jest.fn(),
};

export const store = {
  queries: {
    useInventory: withMockSWR(jest.fn()),
    useOrderById: withMockSWR(jest.fn()),
  },

  mutations: {
    useDeleteOrder: withMockSWRMutation(jest.fn()),
    usePlaceOrder: withMockSWRMutation(jest.fn()),
  },

  // queryKeys are pure functions — no mocking needed
  queryKeys: realApi.store.queryKeys,
};

export const userClient = {
  createUser: jest.fn(),
  createUsersWithListInput: jest.fn(),
  deleteUser: jest.fn(),
  getUserByName: jest.fn(),
  loginUser: jest.fn(),
  logoutUser: jest.fn(),
  updateUser: jest.fn(),
};

export const user = {
  queries: {
    useUserByName: withMockSWR(jest.fn()),
    useLoginUser: withMockSWR(jest.fn()),
    useLogoutUser: withMockSWR(jest.fn()),
  },

  mutations: {
    useCreateUser: withMockSWRMutation(jest.fn()),
    useCreateUsersWithListInput: withMockSWRMutation(jest.fn()),
    useDeleteUser: withMockSWRMutation(jest.fn()),
    useUpdateUser: withMockSWRMutation(jest.fn()),
  },

  // queryKeys are pure functions — no mocking needed
  queryKeys: realApi.user.queryKeys,
};

