'use client';
/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file

import useSWR, { type SWRConfiguration, type Key } from 'swr';
import useSWRMutation, { type SWRMutationConfiguration } from 'swr/mutation';

interface SwrConfig extends SWRConfiguration {
  /* Custom key for SWR. You don't have to worry about this as by default it's the URL. You can use standard SWR Key here if you need more flexibility. */
  key?: Key;
}
import type { AxiosRequestConfig } from 'axios';
import * as API from './swr-axios-split';


export const pet = {
  queries: {
   /**
    * Finds Pets
    * Find pets using different filters
    * @param queryParams (optional) - Grouped query parameters object (status, name, type, owner, sortBy, order, page, limit, city, registrationDate)
    */
    useFindPets(
      queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: AxiosRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? pet.queryKeys.findPets(queryParams, );

      const { data, error, isLoading, mutate } = useSWR<API.Pet[]>(
        cacheUrl,
        () => API.petClient.findPets(queryParams, $httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

   /**
    * Finds Pets by tags
    * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
    * @deprecated
    * @param tags (optional) - Tags to filter by
    */
    useFindPetsByTags(
      tags?: string[] | null,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: AxiosRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? pet.queryKeys.findPetsByTags(tags, );

      const { data, error, isLoading, mutate } = useSWR<API.Pet[]>(
        cacheUrl,
        () => API.petClient.findPetsByTags(tags, $httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

   /**
    * Find pet by ID
    * Returns a single pet
    * @param petId - ID of the pet
    */
    usePetById(
      petId: number,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: AxiosRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? pet.queryKeys.petById(petId, );

      const { data, error, isLoading, mutate } = useSWR<API.Pet>(
        cacheUrl,
        () => API.petClient.getPetById(petId, $httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

  },

  mutations: {
   /**
    * Add a new pet to the store
    * @param body
    */
    useAddPet(
      $config?: SWRMutationConfiguration<API.Pet, Error, string, { body: API.Pet }>,
      $httpConfig?: AxiosRequestConfig    ) {
      return useSWRMutation<API.Pet, Error, string, { body: API.Pet }>(
        '/pet',
        (_key: string, { arg }: { arg: { body: API.Pet } }) =>
          API.petClient.addPet(arg.body, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Deletes a pet
    * @param apiKey (optional) (API name: api_key)
    * @param petId - ID of the pet
    */
    useDeletePet(
      $config?: SWRMutationConfiguration<unknown, Error, string, { apiKey: string | null; petId: number }>,
      $httpConfig?: AxiosRequestConfig    ) {
      return useSWRMutation<unknown, Error, string, { apiKey: string | null; petId: number }>(
        '/pet/*',
        (_key: string, { arg }: { arg: { apiKey: string | null; petId: number } }) =>
          API.petClient.deletePet(arg.apiKey, arg.petId, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Update an existing pet by Id
    * @param body
    */
    useUpdatePet(
      $config?: SWRMutationConfiguration<API.Pet, Error, string, { body: API.Pet }>,
      $httpConfig?: AxiosRequestConfig    ) {
      return useSWRMutation<API.Pet, Error, string, { body: API.Pet }>(
        '/pet',
        (_key: string, { arg }: { arg: { body: API.Pet } }) =>
          API.petClient.updatePet(arg.body, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Updates a pet in the store with form data
    * @param petId - ID of the pet
    * @param queryParams (optional) - Grouped query parameters object (name, status)
    */
    useUpdatePetWithForm(
      $config?: SWRMutationConfiguration<unknown, Error, string, { petId: number; queryParams?: { name?: string | null; status?: string | null; } | null }>,
      $httpConfig?: AxiosRequestConfig    ) {
      return useSWRMutation<unknown, Error, string, { petId: number; queryParams?: { name?: string | null; status?: string | null; } | null }>(
        '/pet/*',
        (_key: string, { arg }: { arg: { petId: number; queryParams?: { name?: string | null; status?: string | null; } | null } }) =>
          API.petClient.updatePetWithForm(arg.petId, arg.queryParams, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * uploads an image
    * @param body (optional)
    * @param petId - ID of the pet
    * @param additionalMetadata (optional) - Additional Metadata
    */
    useUploadFile(
      $config?: SWRMutationConfiguration<API.File, Error, string, { body: API.File | null; petId: number; additionalMetadata?: string | null }>,
      $httpConfig?: AxiosRequestConfig    ) {
      return useSWRMutation<API.File, Error, string, { body: API.File | null; petId: number; additionalMetadata?: string | null }>(
        '/pet/*/uploadImage',
        (_key: string, { arg }: { arg: { body: API.File | null; petId: number; additionalMetadata?: string | null } }) =>
          API.petClient.uploadFile(arg.body, arg.petId, arg.additionalMetadata, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

  },

  queryKeys: {
    findPets: (queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null, ) => `/pet/find?${API.encodeParams({'status': queryParams?.status, 'name': queryParams?.name, 'type': queryParams?.type, 'owner': queryParams?.owner, 'sortBy': queryParams?.sortBy, 'order': queryParams?.order, 'page': queryParams?.page, 'limit': queryParams?.limit, 'city': queryParams?.city, 'registrationDate': queryParams?.registrationDate, })}`,
    findPetsByTags: (tags?: string[] | null, ) => `/pet/findByTags?${API.encodeParams({'tags': tags, })}`,
    petById: (petId: number, ) => `/pet/${encodeURIComponent(`${petId}`)}`,
  },
};

export const store = {
  queries: {
   /**
    * Returns pet inventories by status
    * Returns a map of status codes to quantities
    */
    useInventory(
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: AxiosRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? store.queryKeys.inventory();

      const { data, error, isLoading, mutate } = useSWR<Record<string, number>>(
        cacheUrl,
        () => API.storeClient.getInventory($httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

   /**
    * Find purchase order by ID
    * For valid response try integer IDs with value &le; 5 or &gt; 10. Other values will generate exceptions.
    * @param orderId - ID of order that needs to be fetched
    */
    useOrderById(
      orderId: number,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: AxiosRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? store.queryKeys.orderById(orderId, );

      const { data, error, isLoading, mutate } = useSWR<API.Order>(
        cacheUrl,
        () => API.storeClient.getOrderById(orderId, $httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

  },

  mutations: {
   /**
    * Delete purchase order by ID
    * For valid response try integer IDs with value &lt; 1000. Anything above 1000 or nonintegers will generate API errors
    * @param orderId - ID of the order that needs to be deleted
    */
    useDeleteOrder(
      $config?: SWRMutationConfiguration<unknown, Error, string, { orderId: number }>,
      $httpConfig?: AxiosRequestConfig    ) {
      return useSWRMutation<unknown, Error, string, { orderId: number }>(
        '/store/order/*',
        (_key: string, { arg }: { arg: { orderId: number } }) =>
          API.storeClient.deleteOrder(arg.orderId, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Place an order for a pet
    * Place a new order in the store
    * @param body (optional)
    */
    usePlaceOrder(
      $config?: SWRMutationConfiguration<API.Order, Error, string, { body?: API.Order | null }>,
      $httpConfig?: AxiosRequestConfig    ) {
      return useSWRMutation<API.Order, Error, string, { body?: API.Order | null }>(
        '/store/order',
        (_key: string, { arg }: { arg: { body?: API.Order | null } }) =>
          API.storeClient.placeOrder(arg.body, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

  },

  queryKeys: {
    inventory: () => `/store/inventory`,
    orderById: (orderId: number, ) => `/store/order/${encodeURIComponent(`${orderId}`)}`,
  },
};

export const user = {
  queries: {
   /**
    * Get user by user name
    * @param username - The name that needs to be fetched. Use user1 for testing.
    */
    useUserByName(
      username: string,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: AxiosRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? user.queryKeys.userByName(username, );

      const { data, error, isLoading, mutate } = useSWR<API.User>(
        cacheUrl,
        () => API.userClient.getUserByName(username, $httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

   /**
    * Logs user into the system
    * @param queryParams (optional) - Grouped query parameters object (username, password)
    */
    useLoginUser(
      queryParams?: { username?: string | null; password?: string | null; } | null,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: AxiosRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? user.queryKeys.loginUser(queryParams, );

      const { data, error, isLoading, mutate } = useSWR<string>(
        cacheUrl,
        () => API.userClient.loginUser(queryParams, $httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

  /** Logs out current logged in user session */
    useLogoutUser(
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: AxiosRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? user.queryKeys.logoutUser();

      const { data, error, isLoading, mutate } = useSWR<unknown>(
        cacheUrl,
        () => API.userClient.logoutUser($httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

  },

  mutations: {
   /**
    * Create user
    * This can only be done by the logged in user.
    * @param body (optional)
    */
    useCreateUser(
      $config?: SWRMutationConfiguration<API.User, Error, string, { body?: API.User | null }>,
      $httpConfig?: AxiosRequestConfig    ) {
      return useSWRMutation<API.User, Error, string, { body?: API.User | null }>(
        '/user',
        (_key: string, { arg }: { arg: { body?: API.User | null } }) =>
          API.userClient.createUser(arg.body, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Creates list of users with given input array
    * @param body (optional)
    */
    useCreateUsersWithListInput(
      $config?: SWRMutationConfiguration<API.User, Error, string, { body?: API.User[] | null }>,
      $httpConfig?: AxiosRequestConfig    ) {
      return useSWRMutation<API.User, Error, string, { body?: API.User[] | null }>(
        '/user/createWithList',
        (_key: string, { arg }: { arg: { body?: API.User[] | null } }) =>
          API.userClient.createUsersWithListInput(arg.body, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Delete user
    * This can only be done by the logged in user.
    * @param username - The name that needs to be deleted
    */
    useDeleteUser(
      $config?: SWRMutationConfiguration<unknown, Error, string, { username: string }>,
      $httpConfig?: AxiosRequestConfig    ) {
      return useSWRMutation<unknown, Error, string, { username: string }>(
        '/user/*',
        (_key: string, { arg }: { arg: { username: string } }) =>
          API.userClient.deleteUser(arg.username, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Update user
    * This can only be done by the logged in user.
    * @param body (optional)
    * @param username - name that needs to be updated
    */
    useUpdateUser(
      $config?: SWRMutationConfiguration<unknown, Error, string, { body: API.FormData | null; username: string }>,
      $httpConfig?: AxiosRequestConfig    ) {
      return useSWRMutation<unknown, Error, string, { body: API.FormData | null; username: string }>(
        '/user/*',
        (_key: string, { arg }: { arg: { body: API.FormData | null; username: string } }) =>
          API.userClient.updateUser(arg.body, arg.username, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

  },

  queryKeys: {
    userByName: (username: string, ) => `/user/${encodeURIComponent(`${username}`)}`,
    loginUser: (queryParams?: { username?: string | null; password?: string | null; } | null, ) => `/user/login?${API.encodeParams({'username': queryParams?.username, 'password': queryParams?.password, })}`,
    logoutUser: () => `/user/logout`,
  },
};
