/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file

import useSWR, { type SWRConfiguration, type Key } from 'swr';
import useSWRMutation, { type SWRMutationConfiguration } from 'swr/mutation';

interface SwrConfig extends SWRConfiguration {
  /* Custom key for SWR. You don't have to worry about this as by default it's the URL. You can use standard SWR Key here if you need more flexibility. */
  key?: Key;
}
import xior, { type XiorResponse, type XiorRequestConfig, encodeParams } from "xior";

export const http = xior.create({
  baseURL: '',
  paramsSerializer: (params: any) =>
    encodeParams(params, true, null, {
      allowDots: true,
      arrayFormat: 'repeat',
    }),
});

export const petClient = {
   /**
  * Add a new pet to the store
  * @param body
  */
  addPet(body: Pet ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Pet>> {
    const url = `/pet`;

    return http.request<Pet>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

   /**
  * Deletes a pet
  * @param apiKey (optional) (API name: api_key)
  * @param petId - ID of the pet
  */
  deletePet(apiKey: string | null | undefined,
    petId: number ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<unknown>> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;

    return http.request<unknown>({
      url: url,
      method: 'DELETE',
      headers: {
        'api_key': apiKey,
      },
      ...$config,
    });
  },

   /**
  * Finds Pets
  * Find pets using different filters
  * @param queryParams (optional) - Grouped query parameters object (status, name, type, owner, sortBy, order, page, limit, city, registrationDate)
  */
  findPets(queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Pet[]>> {
    const url = `/pet/find`;

    return http.request<Pet[]>({
      url: url,
      method: 'GET',
      params: {
        'status': queryParams?.status,
        'name': queryParams?.name,
        'type': queryParams?.type,
        'owner': queryParams?.owner,
        'sortBy': queryParams?.sortBy,
        'order': queryParams?.order,
        'page': queryParams?.page,
        'limit': queryParams?.limit,
        'city': queryParams?.city,
        'registrationDate': queryParams?.registrationDate,
      },
      ...$config,
    });
  },

   /**
  * Finds Pets by tags
  * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
  * @deprecated
  * @param tags (optional) - Tags to filter by
  */
  findPetsByTags(tags?: string[] | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Pet[]>> {
    const url = `/pet/findByTags`;

    return http.request<Pet[]>({
      url: url,
      method: 'GET',
      params: {
        'tags': tags,
      },
      ...$config,
    });
  },

   /**
  * Find pet by ID
  * Returns a single pet
  * @param petId - ID of the pet
  */
  getPetById(petId: number ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Pet>> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;

    return http.request<Pet>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

   /**
  * Update an existing pet by Id
  * @param body
  */
  updatePet(body: Pet ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Pet>> {
    const url = `/pet`;

    return http.request<Pet>({
      url: url,
      method: 'PUT',
      data: new URLSearchParams(body as any),
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      ...$config,
    });
  },

   /**
  * Updates a pet in the store with form data
  * @param petId - ID of the pet
  * @param queryParams (optional) - Grouped query parameters object (name, status)
  */
  updatePetWithForm(petId: number ,
    queryParams?: { name?: string | null; status?: string | null; } | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<unknown>> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;

    return http.request<unknown>({
      url: url,
      method: 'POST',
      params: {
        'name': queryParams?.name,
        'status': queryParams?.status,
      },
      ...$config,
    });
  },

   /**
  * uploads an image
  * @param body (optional)
  * @param petId - ID of the pet
  * @param additionalMetadata (optional) - Additional Metadata
  */
  uploadFile(body: File | null | undefined,
    petId: number ,
    additionalMetadata?: string | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<File>> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}/uploadImage`;

    return http.request<File>({
      url: url,
      method: 'POST',
      data: body,
      params: {
        'additionalMetadata': additionalMetadata,
      },
      ...$config,
    });
  },

  };


export const pet = {
  queries: {
   /**
    * Finds Pets
    * Find pets using different filters
    * @param queryParams (optional) - Grouped query parameters object (status, name, type, owner, sortBy, order, page, limit, city, registrationDate)
    */
    useFindPets(
      queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: XiorRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? pet.queryKeys.findPets(queryParams, );

      const { data, error, isLoading, mutate } = useSWR<Pet[]>(
        cacheUrl,
        () => petClient.findPets(queryParams, $httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

   /**
    * Finds Pets by tags
    * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
    * @deprecated
    * @param tags (optional) - Tags to filter by
    */
    useFindPetsByTags(
      tags?: string[] | null,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: XiorRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? pet.queryKeys.findPetsByTags(tags, );

      const { data, error, isLoading, mutate } = useSWR<Pet[]>(
        cacheUrl,
        () => petClient.findPetsByTags(tags, $httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

   /**
    * Find pet by ID
    * Returns a single pet
    * @param petId - ID of the pet
    */
    usePetById(
      petId: number,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: XiorRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? pet.queryKeys.petById(petId, );

      const { data, error, isLoading, mutate } = useSWR<Pet>(
        cacheUrl,
        () => petClient.getPetById(petId, $httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

  },

  mutations: {
   /**
    * Add a new pet to the store
    * @param body
    */
    useAddPet(
      $config?: SWRMutationConfiguration<Pet, Error, string, { body: Pet }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useSWRMutation<Pet, Error, string, { body: Pet }>(
        '/pet',
        (_key: string, { arg }: { arg: { body: Pet } }) =>
          petClient.addPet(arg.body, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Deletes a pet
    * @param apiKey (optional) (API name: api_key)
    * @param petId - ID of the pet
    */
    useDeletePet(
      $config?: SWRMutationConfiguration<unknown, Error, string, { apiKey: string | null; petId: number }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useSWRMutation<unknown, Error, string, { apiKey: string | null; petId: number }>(
        '/pet/*',
        (_key: string, { arg }: { arg: { apiKey: string | null; petId: number } }) =>
          petClient.deletePet(arg.apiKey, arg.petId, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Update an existing pet by Id
    * @param body
    */
    useUpdatePet(
      $config?: SWRMutationConfiguration<Pet, Error, string, { body: Pet }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useSWRMutation<Pet, Error, string, { body: Pet }>(
        '/pet',
        (_key: string, { arg }: { arg: { body: Pet } }) =>
          petClient.updatePet(arg.body, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Updates a pet in the store with form data
    * @param petId - ID of the pet
    * @param queryParams (optional) - Grouped query parameters object (name, status)
    */
    useUpdatePetWithForm(
      $config?: SWRMutationConfiguration<unknown, Error, string, { petId: number; queryParams?: { name?: string | null; status?: string | null; } | null }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useSWRMutation<unknown, Error, string, { petId: number; queryParams?: { name?: string | null; status?: string | null; } | null }>(
        '/pet/*',
        (_key: string, { arg }: { arg: { petId: number; queryParams?: { name?: string | null; status?: string | null; } | null } }) =>
          petClient.updatePetWithForm(arg.petId, arg.queryParams, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * uploads an image
    * @param body (optional)
    * @param petId - ID of the pet
    * @param additionalMetadata (optional) - Additional Metadata
    */
    useUploadFile(
      $config?: SWRMutationConfiguration<File, Error, string, { body: File | null; petId: number; additionalMetadata?: string | null }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useSWRMutation<File, Error, string, { body: File | null; petId: number; additionalMetadata?: string | null }>(
        '/pet/*/uploadImage',
        (_key: string, { arg }: { arg: { body: File | null; petId: number; additionalMetadata?: string | null } }) =>
          petClient.uploadFile(arg.body, arg.petId, arg.additionalMetadata, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

  },

  queryKeys: {
    findPets: (queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null, ) => `/pet/find?${encodeParams({'status': queryParams?.status, 'name': queryParams?.name, 'type': queryParams?.type, 'owner': queryParams?.owner, 'sortBy': queryParams?.sortBy, 'order': queryParams?.order, 'page': queryParams?.page, 'limit': queryParams?.limit, 'city': queryParams?.city, 'registrationDate': queryParams?.registrationDate, })}`,
    findPetsByTags: (tags?: string[] | null, ) => `/pet/findByTags?${encodeParams({'tags': tags, })}`,
    petById: (petId: number, ) => `/pet/${encodeURIComponent(`${petId}`)}`,
  },
};
export const storeClient = {
   /**
  * Delete purchase order by ID
  * For valid response try integer IDs with value &lt; 1000. Anything above 1000 or nonintegers will generate API errors
  * @param orderId - ID of the order that needs to be deleted
  */
  deleteOrder(orderId: number ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<unknown>> {
    const url = `/store/order/${encodeURIComponent(`${orderId}`)}`;

    return http.request<unknown>({
      url: url,
      method: 'DELETE',
      ...$config,
    });
  },

   /**
  * Returns pet inventories by status
  * Returns a map of status codes to quantities
  */
  getInventory($config?: XiorRequestConfig
  ): Promise<XiorResponse<Record<string, number>>> {
    const url = `/store/inventory`;

    return http.request<Record<string, number>>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

   /**
  * Find purchase order by ID
  * For valid response try integer IDs with value &le; 5 or &gt; 10. Other values will generate exceptions.
  * @param orderId - ID of order that needs to be fetched
  */
  getOrderById(orderId: number ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Order>> {
    const url = `/store/order/${encodeURIComponent(`${orderId}`)}`;

    return http.request<Order>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

   /**
  * Place an order for a pet
  * Place a new order in the store
  * @param body (optional)
  */
  placeOrder(body?: Order | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Order>> {
    const url = `/store/order`;

    return http.request<Order>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

  };


export const store = {
  queries: {
   /**
    * Returns pet inventories by status
    * Returns a map of status codes to quantities
    */
    useInventory(
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: XiorRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? store.queryKeys.inventory();

      const { data, error, isLoading, mutate } = useSWR<Record<string, number>>(
        cacheUrl,
        () => storeClient.getInventory($httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

   /**
    * Find purchase order by ID
    * For valid response try integer IDs with value &le; 5 or &gt; 10. Other values will generate exceptions.
    * @param orderId - ID of order that needs to be fetched
    */
    useOrderById(
      orderId: number,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: XiorRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? store.queryKeys.orderById(orderId, );

      const { data, error, isLoading, mutate } = useSWR<Order>(
        cacheUrl,
        () => storeClient.getOrderById(orderId, $httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

  },

  mutations: {
   /**
    * Delete purchase order by ID
    * For valid response try integer IDs with value &lt; 1000. Anything above 1000 or nonintegers will generate API errors
    * @param orderId - ID of the order that needs to be deleted
    */
    useDeleteOrder(
      $config?: SWRMutationConfiguration<unknown, Error, string, { orderId: number }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useSWRMutation<unknown, Error, string, { orderId: number }>(
        '/store/order/*',
        (_key: string, { arg }: { arg: { orderId: number } }) =>
          storeClient.deleteOrder(arg.orderId, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Place an order for a pet
    * Place a new order in the store
    * @param body (optional)
    */
    usePlaceOrder(
      $config?: SWRMutationConfiguration<Order, Error, string, { body?: Order | null }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useSWRMutation<Order, Error, string, { body?: Order | null }>(
        '/store/order',
        (_key: string, { arg }: { arg: { body?: Order | null } }) =>
          storeClient.placeOrder(arg.body, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

  },

  queryKeys: {
    inventory: () => `/store/inventory`,
    orderById: (orderId: number, ) => `/store/order/${encodeURIComponent(`${orderId}`)}`,
  },
};
export const userClient = {
   /**
  * Create user
  * This can only be done by the logged in user.
  * @param body (optional)
  */
  createUser(body?: User | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<User>> {
    const url = `/user`;

    return http.request<User>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

   /**
  * Creates list of users with given input array
  * @param body (optional)
  */
  createUsersWithListInput(body?: User[] | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<User>> {
    const url = `/user/createWithList`;

    return http.request<User>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

   /**
  * Delete user
  * This can only be done by the logged in user.
  * @param username - The name that needs to be deleted
  */
  deleteUser(username: string ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<unknown>> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;

    return http.request<unknown>({
      url: url,
      method: 'DELETE',
      ...$config,
    });
  },

   /**
  * Get user by user name
  * @param username - The name that needs to be fetched. Use user1 for testing.
  */
  getUserByName(username: string ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<User>> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;

    return http.request<User>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

   /**
  * Logs user into the system
  * @param queryParams (optional) - Grouped query parameters object (username, password)
  */
  loginUser(queryParams?: { username?: string | null; password?: string | null; } | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<string>> {
    const url = `/user/login`;

    return http.request<string>({
      url: url,
      method: 'GET',
      params: {
        'username': queryParams?.username,
        'password': queryParams?.password,
      },
      ...$config,
    });
  },

  /** Logs out current logged in user session */
  logoutUser($config?: XiorRequestConfig
  ): Promise<XiorResponse<unknown>> {
    const url = `/user/logout`;

    return http.request<unknown>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

   /**
  * Update user
  * This can only be done by the logged in user.
  * @param body (optional)
  * @param username - name that needs to be updated
  */
  updateUser(body: FormData | null | undefined,
    username: string ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<unknown>> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;

    return http.request<unknown>({
      url: url,
      method: 'PUT',
      data: body,
      ...$config,
    });
  },

  };


export const user = {
  queries: {
   /**
    * Get user by user name
    * @param username - The name that needs to be fetched. Use user1 for testing.
    */
    useUserByName(
      username: string,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: XiorRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? user.queryKeys.userByName(username, );

      const { data, error, isLoading, mutate } = useSWR<User>(
        cacheUrl,
        () => userClient.getUserByName(username, $httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

   /**
    * Logs user into the system
    * @param queryParams (optional) - Grouped query parameters object (username, password)
    */
    useLoginUser(
      queryParams?: { username?: string | null; password?: string | null; } | null,
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: XiorRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? user.queryKeys.loginUser(queryParams, );

      const { data, error, isLoading, mutate } = useSWR<string>(
        cacheUrl,
        () => userClient.loginUser(queryParams, $httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

  /** Logs out current logged in user session */
    useLogoutUser(
      $config?: Omit<SwrConfig, 'key'> & { key?: Key },
      $httpConfig?: XiorRequestConfig    ) {
      const { key, ...config } = $config || {};
      const cacheUrl = key ?? user.queryKeys.logoutUser();

      const { data, error, isLoading, mutate } = useSWR<unknown>(
        cacheUrl,
        () => userClient.logoutUser($httpConfig).then((resp) =&gt; resp.data),
        config
      );

      return { data, isLoading, error, mutate };
    },

  },

  mutations: {
   /**
    * Create user
    * This can only be done by the logged in user.
    * @param body (optional)
    */
    useCreateUser(
      $config?: SWRMutationConfiguration<User, Error, string, { body?: User | null }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useSWRMutation<User, Error, string, { body?: User | null }>(
        '/user',
        (_key: string, { arg }: { arg: { body?: User | null } }) =>
          userClient.createUser(arg.body, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Creates list of users with given input array
    * @param body (optional)
    */
    useCreateUsersWithListInput(
      $config?: SWRMutationConfiguration<User, Error, string, { body?: User[] | null }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useSWRMutation<User, Error, string, { body?: User[] | null }>(
        '/user/createWithList',
        (_key: string, { arg }: { arg: { body?: User[] | null } }) =>
          userClient.createUsersWithListInput(arg.body, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Delete user
    * This can only be done by the logged in user.
    * @param username - The name that needs to be deleted
    */
    useDeleteUser(
      $config?: SWRMutationConfiguration<unknown, Error, string, { username: string }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useSWRMutation<unknown, Error, string, { username: string }>(
        '/user/*',
        (_key: string, { arg }: { arg: { username: string } }) =>
          userClient.deleteUser(arg.username, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

   /**
    * Update user
    * This can only be done by the logged in user.
    * @param body (optional)
    * @param username - name that needs to be updated
    */
    useUpdateUser(
      $config?: SWRMutationConfiguration<unknown, Error, string, { body: FormData | null; username: string }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useSWRMutation<unknown, Error, string, { body: FormData | null; username: string }>(
        '/user/*',
        (_key: string, { arg }: { arg: { body: FormData | null; username: string } }) =>
          userClient.updateUser(arg.body, arg.username, $httpConfig).then((resp) =&gt; resp.data),
        $config
      );
    },

  },

  queryKeys: {
    userByName: (username: string, ) => `/user/${encodeURIComponent(`${username}`)}`,
    loginUser: (queryParams?: { username?: string | null; password?: string | null; } | null, ) => `/user/login?${encodeParams({'username': queryParams?.username, 'password': queryParams?.password, })}`,
    logoutUser: () => `/user/logout`,
  },
};
export { encodeParams } from 'xior';
export interface Order {
  /** @format int64 */
  id?: number;
  /** @format int64 */
  petId?: number;
  /** @format int32 */
  quantity?: number;
  /** @format date-time */
  shipDate?: Date;
  /** Order Status */
  status?: "placed" | "approved" | "delivered";
  complete?: boolean;
}

export type Category = { id?: number;
name?: string; } & Record<string, boolean>;

export type User = { id: number;
username?: string;
firstName?: string;
lastName?: string;
email: string;
password?: string;
phone?: string | null;
userStatus?: number; } | { id: number;
username: string;
firstName?: string;
lastName?: string;
email?: string;
password?: string;
phone?: string | null;
userStatus?: number; };

export interface Tag {
  /** @format int64 */
  id?: number;
  name?: string;
}

export type Pet = { id?: number;
name: string;
category?: Category;
photoUrls: string[] | null;
tags?: Tag[];
status?: "available" | "pending" | "sold"; } & Record<string, Item>;

export type Item = Record<string, Tag>;
