/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file
import { jest } from '@jest/globals';
import type { KeyedMutator } from 'swr';

import * as realApi from './api';
import * as realHooks from './hooks';

const defaultSWRReturn = {
  data: undefined,
  isLoading: false,
  error: undefined,
  mutate: jest.fn() as unknown as KeyedMutator<any>,
  isValidating: false,
};

const defaultSWRMutationReturn = {
  trigger: jest.fn(() => Promise.resolve(undefined)),
  isMutating: false,
  error: undefined,
  data: undefined,
  reset: jest.fn(),
};

interface MockSWRReturn {
  /** The data to return from the mock */
  data: unknown;
  /** Whether to return a loading state (default: false) */
  isLoading?: boolean;
  /** Whether to return an error (default: undefined) */
  error?: Error | undefined | null;
}

interface MockSWRMutationReturn {
  /** The data to return from the mock */
  data: unknown;
  /** Whether to return a mutating state (default: false) */
  isMutating?: boolean;
  /** Whether to return an error (default: undefined) */
  error?: Error | undefined | null;
}

/** Augments a spy with a `mockSWR` shorthand for useSWR query hooks. */
function withMockSWR<Fn extends (...args: never[]) => unknown>(spy: jest.SpiedFunction<Fn>) {
  return Object.assign(spy, {
    mockSWR({ data, isLoading, error }: MockSWRReturn) {
      spy.mockReturnValue({
        ...defaultSWRReturn,
        data,
        isLoading: isLoading ?? false,
        error: error ?? undefined,
      } as ReturnType<Fn>);
    },
  });
}

/** Augments a spy with a `mockSWRMutation` shorthand for useSWRMutation hooks. */
function withMockSWRMutation<Fn extends (...args: never[]) => unknown>(spy: jest.SpiedFunction<Fn>) {
  return Object.assign(spy, {
    mockSWRMutation({
      data,
      isMutating,
      error,
    }: MockSWRMutationReturn) {
      spy.mockReturnValue({
        ...defaultSWRMutationReturn,
        trigger: jest.fn(() => Promise.resolve(undefined)),
        isMutating: isMutating ?? false,
        error: error ?? undefined,
        data,
      } as ReturnType<Fn>);
    },
  });
}

export function createClientMocks() {
  return {
    petClient: {
      addPet: jest.spyOn(realApi.petClient, 'addPet').mockReturnValue(undefined as any),
      deletePet: jest.spyOn(realApi.petClient, 'deletePet').mockReturnValue(undefined as any),
      findPets: jest.spyOn(realApi.petClient, 'findPets').mockReturnValue(undefined as any),
      findPetsByTags: jest.spyOn(realApi.petClient, 'findPetsByTags').mockReturnValue(undefined as any),
      getPetById: jest.spyOn(realApi.petClient, 'getPetById').mockReturnValue(undefined as any),
      updatePet: jest.spyOn(realApi.petClient, 'updatePet').mockReturnValue(undefined as any),
      updatePetWithForm: jest.spyOn(realApi.petClient, 'updatePetWithForm').mockReturnValue(undefined as any),
      uploadFile: jest.spyOn(realApi.petClient, 'uploadFile').mockReturnValue(undefined as any),
    },
    storeClient: {
      deleteOrder: jest.spyOn(realApi.storeClient, 'deleteOrder').mockReturnValue(undefined as any),
      getInventory: jest.spyOn(realApi.storeClient, 'getInventory').mockReturnValue(undefined as any),
      getOrderById: jest.spyOn(realApi.storeClient, 'getOrderById').mockReturnValue(undefined as any),
      placeOrder: jest.spyOn(realApi.storeClient, 'placeOrder').mockReturnValue(undefined as any),
    },
    userClient: {
      createUser: jest.spyOn(realApi.userClient, 'createUser').mockReturnValue(undefined as any),
      createUsersWithListInput: jest.spyOn(realApi.userClient, 'createUsersWithListInput').mockReturnValue(undefined as any),
      deleteUser: jest.spyOn(realApi.userClient, 'deleteUser').mockReturnValue(undefined as any),
      getUserByName: jest.spyOn(realApi.userClient, 'getUserByName').mockReturnValue(undefined as any),
      loginUser: jest.spyOn(realApi.userClient, 'loginUser').mockReturnValue(undefined as any),
      logoutUser: jest.spyOn(realApi.userClient, 'logoutUser').mockReturnValue(undefined as any),
      updateUser: jest.spyOn(realApi.userClient, 'updateUser').mockReturnValue(undefined as any),
    },
  };
}

export type ClientMocks = ReturnType<typeof createClientMocks>;

export function createApiHookMocks() {
  return {
    pet: {
      queries: {
        useFindPets: withMockSWR(jest.spyOn(realHooks.pet.queries, 'useFindPets').mockReturnValue(defaultSWRReturn)),
        useFindPetsByTags: withMockSWR(jest.spyOn(realHooks.pet.queries, 'useFindPetsByTags').mockReturnValue(defaultSWRReturn)),
        usePetById: withMockSWR(jest.spyOn(realHooks.pet.queries, 'usePetById').mockReturnValue(defaultSWRReturn)),
      },
      mutations: {
        useAddPet: withMockSWRMutation(jest.spyOn(realHooks.pet.mutations, 'useAddPet').mockReturnValue(defaultSWRMutationReturn as any)),
        useDeletePet: withMockSWRMutation(jest.spyOn(realHooks.pet.mutations, 'useDeletePet').mockReturnValue(defaultSWRMutationReturn as any)),
        useUpdatePet: withMockSWRMutation(jest.spyOn(realHooks.pet.mutations, 'useUpdatePet').mockReturnValue(defaultSWRMutationReturn as any)),
        useUpdatePetWithForm: withMockSWRMutation(jest.spyOn(realHooks.pet.mutations, 'useUpdatePetWithForm').mockReturnValue(defaultSWRMutationReturn as any)),
        useUploadFile: withMockSWRMutation(jest.spyOn(realHooks.pet.mutations, 'useUploadFile').mockReturnValue(defaultSWRMutationReturn as any)),
      },
    },
    store: {
      queries: {
        useInventory: withMockSWR(jest.spyOn(realHooks.store.queries, 'useInventory').mockReturnValue(defaultSWRReturn)),
        useOrderById: withMockSWR(jest.spyOn(realHooks.store.queries, 'useOrderById').mockReturnValue(defaultSWRReturn)),
      },
      mutations: {
        useDeleteOrder: withMockSWRMutation(jest.spyOn(realHooks.store.mutations, 'useDeleteOrder').mockReturnValue(defaultSWRMutationReturn as any)),
        usePlaceOrder: withMockSWRMutation(jest.spyOn(realHooks.store.mutations, 'usePlaceOrder').mockReturnValue(defaultSWRMutationReturn as any)),
      },
    },
    user: {
      queries: {
        useUserByName: withMockSWR(jest.spyOn(realHooks.user.queries, 'useUserByName').mockReturnValue(defaultSWRReturn)),
        useLoginUser: withMockSWR(jest.spyOn(realHooks.user.queries, 'useLoginUser').mockReturnValue(defaultSWRReturn)),
        useLogoutUser: withMockSWR(jest.spyOn(realHooks.user.queries, 'useLogoutUser').mockReturnValue(defaultSWRReturn)),
      },
      mutations: {
        useCreateUser: withMockSWRMutation(jest.spyOn(realHooks.user.mutations, 'useCreateUser').mockReturnValue(defaultSWRMutationReturn as any)),
        useCreateUsersWithListInput: withMockSWRMutation(jest.spyOn(realHooks.user.mutations, 'useCreateUsersWithListInput').mockReturnValue(defaultSWRMutationReturn as any)),
        useDeleteUser: withMockSWRMutation(jest.spyOn(realHooks.user.mutations, 'useDeleteUser').mockReturnValue(defaultSWRMutationReturn as any)),
        useUpdateUser: withMockSWRMutation(jest.spyOn(realHooks.user.mutations, 'useUpdateUser').mockReturnValue(defaultSWRMutationReturn as any)),
      },
    },
  };
}

export type ApiHookMocks = ReturnType<typeof createApiHookMocks>;
