'use client';
/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file

import { type UseQueryOptions, type UseMutationOptions, useQuery, useMutation } from '@tanstack/react-query';
import type { XiorRequestConfig } from 'xior';
import * as API from './tsq-split';


export const pet = {
  queries: {
   /**
    * Finds Pets
    * Find pets using different filters
    * @param queryParams (optional) - Grouped query parameters object (status, name, type, owner, sortBy, order, page, limit, city, registrationDate)
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useFindPets<TData = API.Pet[], TError = Error>(
      queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null,
      $config?: Omit<UseQueryOptions<API.Pet[], TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig    ) {
      return useQuery<API.Pet[], TError, TData>({
        queryKey: pet.queryKeys.findPets(queryParams, ),
        queryFn: () => API.petClient.findPets(queryParams, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

   /**
    * Finds Pets by tags
    * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
    * @deprecated
    * @param tags (optional) - Tags to filter by
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useFindPetsByTags<TData = API.Pet[], TError = Error>(
      tags?: string[] | null,
      $config?: Omit<UseQueryOptions<API.Pet[], TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig    ) {
      return useQuery<API.Pet[], TError, TData>({
        queryKey: pet.queryKeys.findPetsByTags(tags, ),
        queryFn: () => API.petClient.findPetsByTags(tags, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

   /**
    * Find pet by ID
    * Returns a single pet
    * @param petId - ID of the pet
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    usePetById<TData = API.Pet, TError = Error>(
      petId: number,
      $config?: Omit<UseQueryOptions<API.Pet, TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig    ) {
      return useQuery<API.Pet, TError, TData>({
        queryKey: pet.queryKeys.petById(petId, ),
        queryFn: () => API.petClient.getPetById(petId, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

  },

  mutations: {
   /**
    * Add a new pet to the store
    * @param body
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useAddPet<TData = API.Pet, TError = Error>(
      $config?: UseMutationOptions<API.Pet, TError, { body: API.Pet }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useMutation<API.Pet, TError, { body: API.Pet }>({
        mutationFn: (vars) => API.petClient.addPet(vars.body, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

   /**
    * Deletes a pet
    * @param apiKey (optional) (API name: api_key)
    * @param petId - ID of the pet
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useDeletePet<TData = unknown, TError = Error>(
      $config?: UseMutationOptions<unknown, TError, { apiKey: string | null; petId: number }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useMutation<unknown, TError, { apiKey: string | null; petId: number }>({
        mutationFn: (vars) => API.petClient.deletePet(vars.apiKey, vars.petId, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

   /**
    * Update an existing pet by Id
    * @param body
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useUpdatePet<TData = API.Pet, TError = Error>(
      $config?: UseMutationOptions<API.Pet, TError, { body: API.Pet }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useMutation<API.Pet, TError, { body: API.Pet }>({
        mutationFn: (vars) => API.petClient.updatePet(vars.body, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

   /**
    * Updates a pet in the store with form data
    * @param petId - ID of the pet
    * @param queryParams (optional) - Grouped query parameters object (name, status)
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useUpdatePetWithForm<TData = unknown, TError = Error>(
      $config?: UseMutationOptions<unknown, TError, { petId: number; queryParams?: { name?: string | null; status?: string | null; } | null }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useMutation<unknown, TError, { petId: number; queryParams?: { name?: string | null; status?: string | null; } | null }>({
        mutationFn: (vars) => API.petClient.updatePetWithForm(vars.petId, vars.queryParams, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

   /**
    * uploads an image
    * @param body (optional)
    * @param petId - ID of the pet
    * @param additionalMetadata (optional) - Additional Metadata
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useUploadFile<TData = File, TError = Error>(
      $config?: UseMutationOptions<File, TError, { body: File | null; petId: number; additionalMetadata?: string | null }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useMutation<File, TError, { body: File | null; petId: number; additionalMetadata?: string | null }>({
        mutationFn: (vars) => API.petClient.uploadFile(vars.body, vars.petId, vars.additionalMetadata, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

  },

  queryKeys: {
    findPets: (queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null, ) => ['pet', 'petFindPets', queryParams] as const,
    findPetsByTags: (tags?: string[] | null, ) => ['pet', 'petFindPetsByTags', tags] as const,
    petById: (petId: number, ) => ['pet', 'petPetById', petId] as const,
  },
};

export const store = {
  queries: {
   /**
    * Returns pet inventories by status
    * Returns a map of status codes to quantities
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useInventory<TData = Record<string, number>, TError = Error>(
      $config?: Omit<UseQueryOptions<Record<string, number>, TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig    ) {
      return useQuery<Record<string, number>, TError, TData>({
        queryKey: store.queryKeys.inventory(),
        queryFn: () => API.storeClient.getInventory($httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

   /**
    * Find purchase order by ID
    * For valid response try integer IDs with value &le; 5 or &gt; 10. Other values will generate exceptions.
    * @param orderId - ID of order that needs to be fetched
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useOrderById<TData = API.Order, TError = Error>(
      orderId: number,
      $config?: Omit<UseQueryOptions<API.Order, TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig    ) {
      return useQuery<API.Order, TError, TData>({
        queryKey: store.queryKeys.orderById(orderId, ),
        queryFn: () => API.storeClient.getOrderById(orderId, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

  },

  mutations: {
   /**
    * Delete purchase order by ID
    * For valid response try integer IDs with value &lt; 1000. Anything above 1000 or nonintegers will generate API errors
    * @param orderId - ID of the order that needs to be deleted
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useDeleteOrder<TData = unknown, TError = Error>(
      $config?: UseMutationOptions<unknown, TError, { orderId: number }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useMutation<unknown, TError, { orderId: number }>({
        mutationFn: (vars) => API.storeClient.deleteOrder(vars.orderId, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

   /**
    * Place an order for a pet
    * Place a new order in the store
    * @param body (optional)
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    usePlaceOrder<TData = API.Order, TError = Error>(
      $config?: UseMutationOptions<API.Order, TError, { body?: API.Order | null }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useMutation<API.Order, TError, { body?: API.Order | null }>({
        mutationFn: (vars) => API.storeClient.placeOrder(vars.body, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

  },

  queryKeys: {
    inventory: () => ['store', 'storeInventory'] as const,
    orderById: (orderId: number, ) => ['store', 'storeOrderById', orderId] as const,
  },
};

export const user = {
  queries: {
   /**
    * Get user by user name
    * @param username - The name that needs to be fetched. Use user1 for testing.
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useUserByName<TData = API.User, TError = Error>(
      username: string,
      $config?: Omit<UseQueryOptions<API.User, TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig    ) {
      return useQuery<API.User, TError, TData>({
        queryKey: user.queryKeys.userByName(username, ),
        queryFn: () => API.userClient.getUserByName(username, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

   /**
    * Logs user into the system
    * @param queryParams (optional) - Grouped query parameters object (username, password)
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useLoginUser<TData = string, TError = Error>(
      queryParams?: { username?: string | null; password?: string | null; } | null,
      $config?: Omit<UseQueryOptions<string, TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig    ) {
      return useQuery<string, TError, TData>({
        queryKey: user.queryKeys.loginUser(queryParams, ),
        queryFn: () => API.userClient.loginUser(queryParams, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

  /** Logs out current logged in user session
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useLogoutUser<TData = unknown, TError = Error>(
      $config?: Omit<UseQueryOptions<unknown, TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig    ) {
      return useQuery<unknown, TError, TData>({
        queryKey: user.queryKeys.logoutUser(),
        queryFn: () => API.userClient.logoutUser($httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

  },

  mutations: {
   /**
    * Create user
    * This can only be done by the logged in user.
    * @param body (optional)
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useCreateUser<TData = API.User, TError = Error>(
      $config?: UseMutationOptions<API.User, TError, { body?: API.User | null }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useMutation<API.User, TError, { body?: API.User | null }>({
        mutationFn: (vars) => API.userClient.createUser(vars.body, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

   /**
    * Creates list of users with given input array
    * @param body (optional)
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useCreateUsersWithListInput<TData = API.User, TError = Error>(
      $config?: UseMutationOptions<API.User, TError, { body?: API.User[] | null }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useMutation<API.User, TError, { body?: API.User[] | null }>({
        mutationFn: (vars) => API.userClient.createUsersWithListInput(vars.body, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

   /**
    * Delete user
    * This can only be done by the logged in user.
    * @param username - The name that needs to be deleted
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useDeleteUser<TData = unknown, TError = Error>(
      $config?: UseMutationOptions<unknown, TError, { username: string }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useMutation<unknown, TError, { username: string }>({
        mutationFn: (vars) => API.userClient.deleteUser(vars.username, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

   /**
    * Update user
    * This can only be done by the logged in user.
    * @param body (optional)
    * @param username - name that needs to be updated
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional HTTP client configuration (passed to the underlying XiorRequestConfig)
   */
    useUpdateUser<TData = unknown, TError = Error>(
      $config?: UseMutationOptions<unknown, TError, { body: FormData | null; username: string }>,
      $httpConfig?: XiorRequestConfig    ) {
      return useMutation<unknown, TError, { body: FormData | null; username: string }>({
        mutationFn: (vars) => API.userClient.updateUser(vars.body, vars.username, $httpConfig).then((resp) => resp.data),
        ...$config
      });
    },

  },

  queryKeys: {
    userByName: (username: string, ) => ['user', 'userUserByName', username] as const,
    loginUser: (queryParams?: { username?: string | null; password?: string | null; } | null, ) => ['user', 'userLoginUser', queryParams] as const,
    logoutUser: () => ['user', 'userLogoutUser'] as const,
  },
};
