/* istanbul ignore file -- auto-generated code */
/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file

import xior, { type XiorResponse, type XiorRequestConfig, encodeParams } from "xior";
import { type UseQueryOptions, type UseMutationOptions, useQuery, useMutation } from '@tanstack/react-query';

export const http = xior.create({
  baseURL: '',
  paramsSerializer: (params: any) =>
    encodeParams(params, true, null, {
      allowDots: true,
      arrayFormat: 'repeat',
    }),
});

export const petClient = {
   /**
  * Add a new pet to the store
  * @param body
  */
  addPet(body: Pet ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Pet>> {
    const url = `/pet`;

    return http.request<Pet>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

 /**
  * Deletes a pet
  * @param apiKey (optional) (API name: api_key)
  * @param petId - ID of the pet
  */
  deletePet(apiKey: string | null | undefined,
    petId: number ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<unknown>> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;

    return http.request<unknown>({
      url: url,
      method: 'DELETE',
      headers: {
        'api_key': apiKey,
      },
      ...$config,
    });
  },

 /**
  * Finds Pets
  * Find pets using different filters
  * @param queryParams (optional) - Grouped query parameters object (status, name, type, owner, sortBy, order, page, limit, city, registrationDate)
  */
  findPets(queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Pet[]>> {
    const url = `/pet/find`;

    return http.request<Pet[]>({
      url: url,
      method: 'GET',
      params: {
            'status': queryParams?.status,
                'name': queryParams?.name,
                'type': queryParams?.type,
                'owner': queryParams?.owner,
                'sortBy': queryParams?.sortBy,
                'order': queryParams?.order,
                'page': queryParams?.page,
                'limit': queryParams?.limit,
                'city': queryParams?.city,
                'registrationDate': queryParams?.registrationDate,
          },
      ...$config,
    });
  },

 /**
  * Finds Pets by tags
  * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
  * @deprecated
  * @param tags (optional) - Tags to filter by
  */
  findPetsByTags(tags?: string[] | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Pet[]>> {
    const url = `/pet/findByTags`;

    return http.request<Pet[]>({
      url: url,
      method: 'GET',
      params: {
            'tags': tags,
          },
      ...$config,
    });
  },

 /**
  * Find pet by ID
  * Returns a single pet
  * @param petId - ID of the pet
  */
  getPetById(petId: number ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Pet>> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;

    return http.request<Pet>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

 /**
  * Update an existing pet by Id
  * @param body
  */
  updatePet(body: Pet ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Pet>> {
    const url = `/pet`;

    return http.request<Pet>({
      url: url,
      method: 'PUT',
      data: new URLSearchParams(body as any),
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      ...$config,
    });
  },

 /**
  * Updates a pet in the store with form data
  * @param petId - ID of the pet
  * @param queryParams (optional) - Grouped query parameters object (name, status)
  */
  updatePetWithForm(petId: number ,
    queryParams?: { name?: string | null; status?: string | null; } | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<unknown>> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}`;

    return http.request<unknown>({
      url: url,
      method: 'POST',
      params: {
            'name': queryParams?.name,
                'status': queryParams?.status,
          },
      ...$config,
    });
  },

 /**
  * uploads an image
  * @param body (optional)
  * @param petId - ID of the pet
  * @param additionalMetadata (optional) - Additional Metadata
  */
  uploadFile(body: File | null | undefined,
    petId: number ,
    additionalMetadata?: string | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<File>> {
    const url = `/pet/${encodeURIComponent(`${petId}`)}/uploadImage`;

    return http.request<File>({
      url: url,
      method: 'POST',
      data: body,
      params: {
            'additionalMetadata': additionalMetadata,
          },
      ...$config,
    });
  },

};


export const pet = {
  queries: {
   /**
    * Finds Pets
    * Find pets using different filters
    * @param queryParams (optional) - Grouped query parameters object (status, name, type, owner, sortBy, order, page, limit, city, registrationDate)
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useFindPets<TData = Pet[], TError = Error>(
      queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null,
      $config?: Omit<UseQueryOptions<Pet[], TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useQuery<Pet[], TError, TData>({
        queryKey: pet.queryKeys.findPets(queryParams, ),
        queryFn: () => petClient.findPets(queryParams, $httpConfig).then(res => res.data),
        ...$config
      });
    },

   /**
    * Finds Pets by tags
    * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
    * @deprecated
    * @param tags (optional) - Tags to filter by
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useFindPetsByTags<TData = Pet[], TError = Error>(
      tags?: string[] | null,
      $config?: Omit<UseQueryOptions<Pet[], TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useQuery<Pet[], TError, TData>({
        queryKey: pet.queryKeys.findPetsByTags(tags, ),
        queryFn: () => petClient.findPetsByTags(tags, $httpConfig).then(res => res.data),
        ...$config
      });
    },

   /**
    * Find pet by ID
    * Returns a single pet
    * @param petId - ID of the pet
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    usePetById<TData = Pet, TError = Error>(
      petId: number,
      $config?: Omit<UseQueryOptions<Pet, TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useQuery<Pet, TError, TData>({
        queryKey: pet.queryKeys.petById(petId, ),
        queryFn: () => petClient.getPetById(petId, $httpConfig).then(res => res.data),
        ...$config
      });
    },

  },

  mutations: {
   /**
    * Add a new pet to the store
    * @param body
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useAddPet<TData = Pet, TError = Error>(
      $config?: UseMutationOptions<Pet, TError, { body: Pet }>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useMutation<Pet, TError, { body: Pet }>({
        mutationFn: (vars) => petClient.addPet(vars.body, $httpConfig).then(res => res.data),
        ...$config
      });
    },

   /**
    * Deletes a pet
    * @param apiKey (optional) (API name: api_key)
    * @param petId - ID of the pet
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useDeletePet<TData = unknown, TError = Error>(
      $config?: UseMutationOptions<unknown, TError, { apiKey: string | null; petId: number }>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useMutation<unknown, TError, { apiKey: string | null; petId: number }>({
        mutationFn: (vars) => petClient.deletePet(vars.apiKey, vars.petId, $httpConfig).then(res => res.data),
        ...$config
      });
    },

   /**
    * Update an existing pet by Id
    * @param body
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useUpdatePet<TData = Pet, TError = Error>(
      $config?: UseMutationOptions<Pet, TError, { body: Pet }>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useMutation<Pet, TError, { body: Pet }>({
        mutationFn: (vars) => petClient.updatePet(vars.body, $httpConfig).then(res => res.data),
        ...$config
      });
    },

   /**
    * Updates a pet in the store with form data
    * @param petId - ID of the pet
    * @param queryParams (optional) - Grouped query parameters object (name, status)
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useUpdatePetWithForm<TData = unknown, TError = Error>(
      $config?: UseMutationOptions<unknown, TError, { petId: number; queryParams?: { name?: string | null; status?: string | null; } | null }>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useMutation<unknown, TError, { petId: number; queryParams?: { name?: string | null; status?: string | null; } | null }>({
        mutationFn: (vars) => petClient.updatePetWithForm(vars.petId, vars.queryParams, $httpConfig).then(res => res.data),
        ...$config
      });
    },

   /**
    * uploads an image
    * @param body (optional)
    * @param petId - ID of the pet
    * @param additionalMetadata (optional) - Additional Metadata
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useUploadFile<TData = File, TError = Error>(
      $config?: UseMutationOptions<File, TError, { body: File | null; petId: number; additionalMetadata?: string | null }>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useMutation<File, TError, { body: File | null; petId: number; additionalMetadata?: string | null }>({
        mutationFn: (vars) => petClient.uploadFile(vars.body, vars.petId, vars.additionalMetadata, $httpConfig).then(res => res.data),
        ...$config
      });
    },

  },

  queryKeys: {
    findPets: (queryParams?: { status?: "available" | "pending" | "sold" | null; name?: string | null; type?: string | null; owner?: string | null; sortBy?: string | null; order?: "asc" | "desc" | null; page?: number | null; limit?: number | null; city?: string | null; registrationDate?: Date | null; } | null, ) => ['pet', 'petFindPets', queryParams] as const,
    findPetsByTags: (tags?: string[] | null, ) => ['pet', 'petFindPetsByTags', tags] as const,
    petById: (petId: number, ) => ['pet', 'petPetById', petId] as const,
  },
};
export const storeClient = {
   /**
  * Delete purchase order by ID
  * For valid response try integer IDs with value &lt; 1000. Anything above 1000 or nonintegers will generate API errors
  * @param orderId - ID of the order that needs to be deleted
  */
  deleteOrder(orderId: number ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<unknown>> {
    const url = `/store/order/${encodeURIComponent(`${orderId}`)}`;

    return http.request<unknown>({
      url: url,
      method: 'DELETE',
      ...$config,
    });
  },

 /**
  * Returns pet inventories by status
  * Returns a map of status codes to quantities
  */
  getInventory($config?: XiorRequestConfig
  ): Promise<XiorResponse<Record<string, number>>> {
    const url = `/store/inventory`;

    return http.request<Record<string, number>>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

 /**
  * Find purchase order by ID
  * For valid response try integer IDs with value &le; 5 or &gt; 10. Other values will generate exceptions.
  * @param orderId - ID of order that needs to be fetched
  */
  getOrderById(orderId: number ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Order>> {
    const url = `/store/order/${encodeURIComponent(`${orderId}`)}`;

    return http.request<Order>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

 /**
  * Place an order for a pet
  * Place a new order in the store
  * @param body (optional)
  */
  placeOrder(body?: Order | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<Order>> {
    const url = `/store/order`;

    return http.request<Order>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

};


export const store = {
  queries: {
   /**
    * Returns pet inventories by status
    * Returns a map of status codes to quantities
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useInventory<TData = Record<string, number>, TError = Error>(
      $config?: Omit<UseQueryOptions<Record<string, number>, TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useQuery<Record<string, number>, TError, TData>({
        queryKey: store.queryKeys.inventory(),
        queryFn: () => storeClient.getInventory($httpConfig).then(res => res.data),
        ...$config
      });
    },

   /**
    * Find purchase order by ID
    * For valid response try integer IDs with value &le; 5 or &gt; 10. Other values will generate exceptions.
    * @param orderId - ID of order that needs to be fetched
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useOrderById<TData = Order, TError = Error>(
      orderId: number,
      $config?: Omit<UseQueryOptions<Order, TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useQuery<Order, TError, TData>({
        queryKey: store.queryKeys.orderById(orderId, ),
        queryFn: () => storeClient.getOrderById(orderId, $httpConfig).then(res => res.data),
        ...$config
      });
    },

  },

  mutations: {
   /**
    * Delete purchase order by ID
    * For valid response try integer IDs with value &lt; 1000. Anything above 1000 or nonintegers will generate API errors
    * @param orderId - ID of the order that needs to be deleted
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useDeleteOrder<TData = unknown, TError = Error>(
      $config?: UseMutationOptions<unknown, TError, { orderId: number }>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useMutation<unknown, TError, { orderId: number }>({
        mutationFn: (vars) => storeClient.deleteOrder(vars.orderId, $httpConfig).then(res => res.data),
        ...$config
      });
    },

   /**
    * Place an order for a pet
    * Place a new order in the store
    * @param body (optional)
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    usePlaceOrder<TData = Order, TError = Error>(
      $config?: UseMutationOptions<Order, TError, { body?: Order | null }>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useMutation<Order, TError, { body?: Order | null }>({
        mutationFn: (vars) => storeClient.placeOrder(vars.body, $httpConfig).then(res => res.data),
        ...$config
      });
    },

  },

  queryKeys: {
    inventory: () => ['store', 'storeInventory'] as const,
    orderById: (orderId: number, ) => ['store', 'storeOrderById', orderId] as const,
  },
};
export const userClient = {
   /**
  * Create user
  * This can only be done by the logged in user.
  * @param body (optional)
  */
  createUser(body?: User | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<User>> {
    const url = `/user`;

    return http.request<User>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

 /**
  * Creates list of users with given input array
  * @param body (optional)
  */
  createUsersWithListInput(body?: User[] | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<User>> {
    const url = `/user/createWithList`;

    return http.request<User>({
      url: url,
      method: 'POST',
      data: body,
      ...$config,
    });
  },

 /**
  * Delete user
  * This can only be done by the logged in user.
  * @param username - The name that needs to be deleted
  */
  deleteUser(username: string ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<unknown>> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;

    return http.request<unknown>({
      url: url,
      method: 'DELETE',
      ...$config,
    });
  },

 /**
  * Get user by user name
  * @param username - The name that needs to be fetched. Use user1 for testing.
  */
  getUserByName(username: string ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<User>> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;

    return http.request<User>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

 /**
  * Logs user into the system
  * @param queryParams (optional) - Grouped query parameters object (username, password)
  */
  loginUser(queryParams?: { username?: string | null; password?: string | null; } | null,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<string>> {
    const url = `/user/login`;

    return http.request<string>({
      url: url,
      method: 'GET',
      params: {
            'username': queryParams?.username,
                'password': queryParams?.password,
          },
      ...$config,
    });
  },

/** Logs out current logged in user session */
  logoutUser($config?: XiorRequestConfig
  ): Promise<XiorResponse<unknown>> {
    const url = `/user/logout`;

    return http.request<unknown>({
      url: url,
      method: 'GET',
      ...$config,
    });
  },

 /**
  * Update user
  * This can only be done by the logged in user.
  * @param body (optional)
  * @param username - name that needs to be updated
  */
  updateUser(body: FormData | null | undefined,
    username: string ,
    $config?: XiorRequestConfig
  ): Promise<XiorResponse<unknown>> {
    const url = `/user/${encodeURIComponent(`${username}`)}`;

    return http.request<unknown>({
      url: url,
      method: 'PUT',
      data: body,
      ...$config,
    });
  },

};


export const user = {
  queries: {
   /**
    * Get user by user name
    * @param username - The name that needs to be fetched. Use user1 for testing.
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useUserByName<TData = User, TError = Error>(
      username: string,
      $config?: Omit<UseQueryOptions<User, TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useQuery<User, TError, TData>({
        queryKey: user.queryKeys.userByName(username, ),
        queryFn: () => userClient.getUserByName(username, $httpConfig).then(res => res.data),
        ...$config
      });
    },

   /**
    * Logs user into the system
    * @param queryParams (optional) - Grouped query parameters object (username, password)
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useLoginUser<TData = string, TError = Error>(
      queryParams?: { username?: string | null; password?: string | null; } | null,
      $config?: Omit<UseQueryOptions<string, TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useQuery<string, TError, TData>({
        queryKey: user.queryKeys.loginUser(queryParams, ),
        queryFn: () => userClient.loginUser(queryParams, $httpConfig).then(res => res.data),
        ...$config
      });
    },

  /** Logs out current logged in user session
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useLogoutUser<TData = unknown, TError = Error>(
      $config?: Omit<UseQueryOptions<unknown, TError, TData>, 'queryKey' | 'queryFn'>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useQuery<unknown, TError, TData>({
        queryKey: user.queryKeys.logoutUser(),
        queryFn: () => userClient.logoutUser($httpConfig).then(res => res.data),
        ...$config
      });
    },

  },

  mutations: {
   /**
    * Create user
    * This can only be done by the logged in user.
    * @param body (optional)
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useCreateUser<TData = User, TError = Error>(
      $config?: UseMutationOptions<User, TError, { body?: User | null }>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useMutation<User, TError, { body?: User | null }>({
        mutationFn: (vars) => userClient.createUser(vars.body, $httpConfig).then(res => res.data),
        ...$config
      });
    },

   /**
    * Creates list of users with given input array
    * @param body (optional)
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useCreateUsersWithListInput<TData = User, TError = Error>(
      $config?: UseMutationOptions<User, TError, { body?: User[] | null }>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useMutation<User, TError, { body?: User[] | null }>({
        mutationFn: (vars) => userClient.createUsersWithListInput(vars.body, $httpConfig).then(res => res.data),
        ...$config
      });
    },

   /**
    * Delete user
    * This can only be done by the logged in user.
    * @param username - The name that needs to be deleted
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useDeleteUser<TData = unknown, TError = Error>(
      $config?: UseMutationOptions<unknown, TError, { username: string }>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useMutation<unknown, TError, { username: string }>({
        mutationFn: (vars) => userClient.deleteUser(vars.username, $httpConfig).then(res => res.data),
        ...$config
      });
    },

   /**
    * Update user
    * This can only be done by the logged in user.
    * @param body (optional)
    * @param username - name that needs to be updated
    * @param $config (optional) Additional configuration for TanStack Query
    * @param $httpConfig (optional) Additional configuration for xior request (actually executes the request)
   */
    useUpdateUser<TData = unknown, TError = Error>(
      $config?: UseMutationOptions<unknown, TError, { body: FormData | null; username: string }>,
      $httpConfig?: XiorRequestConfig
    ) {
      return useMutation<unknown, TError, { body: FormData | null; username: string }>({
        mutationFn: (vars) => userClient.updateUser(vars.body, vars.username, $httpConfig).then(res => res.data),
        ...$config
      });
    },

  },

  queryKeys: {
    userByName: (username: string, ) => ['user', 'userUserByName', username] as const,
    loginUser: (queryParams?: { username?: string | null; password?: string | null; } | null, ) => ['user', 'userLoginUser', queryParams] as const,
    logoutUser: () => ['user', 'userLogoutUser'] as const,
  },
};
export interface Order {
  /** @format int64 */
  id?: number;
  /** @format int64 */
  petId?: number;
  /** @format int32 */
  quantity?: number;
  /** @format date-time */
  shipDate?: Date;
  /** Order Status */
  status?: "placed" | "approved" | "delivered";
  complete?: boolean;
}

export type Category = { id?: number;
name?: string; } & Record<string, boolean>;

export type User = { id: number;
username?: string;
firstName?: string;
lastName?: string;
email: string;
password?: string;
phone?: string | null;
userStatus?: number; } | { id: number;
username: string;
firstName?: string;
lastName?: string;
email?: string;
password?: string;
phone?: string | null;
userStatus?: number; };

export interface Tag {
  /** @format int64 */
  id?: number;
  name?: string;
}

export type Pet = { id?: number;
name: string;
category?: Category;
photoUrls: string[] | null;
tags?: Tag[];
status?: "available" | "pending" | "sold"; } & Record<string, Item>;

export type Item = Record<string, Tag>;
