/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file
import { vi } from 'vitest';

import * as realApi from './api';

// ─── TanStack Query mock helpers ─────────────────────────────────────────────

/** Augments a spy with a `mockQuery` shorthand for useQuery hooks. */
function withMockQuery<T extends ReturnType<typeof vi.fn>>(spy: T) {
  return Object.assign(spy, {
    mockQuery({ data, isLoading, error }: { data?: unknown; isLoading?: boolean; error?: Error }) {
      const pending = isLoading ?? false;
      spy.mockReturnValue({
        data,
        isLoading: pending,
        isPending: pending,
        isFetching: false,
        isSuccess: data !== undefined && !pending,
        error: error ?? null,
        refetch: vi.fn(),
        status: pending ? 'pending' : 'success',
      });
    },
  });
}

/** Augments a spy with a `mockMutation` shorthand for useMutation hooks. */
function withMockMutation<T extends ReturnType<typeof vi.fn>>(spy: T) {
  return Object.assign(spy, {
    mockMutation({ data, isPending, error }: { data?: unknown; isPending?: boolean; error?: Error }) {
      spy.mockReturnValue({
        mutate: vi.fn(),
        mutateAsync: vi.fn(),
        isPending: isPending ?? false,
        isSuccess: false,
        error: error ?? null,
        data,
        reset: vi.fn(),
      });
    },
  });
}

export const petClient = {
  addPet: vi.fn(),
  deletePet: vi.fn(),
  findPets: vi.fn(),
  findPetsByTags: vi.fn(),
  getPetById: vi.fn(),
  updatePet: vi.fn(),
  updatePetWithForm: vi.fn(),
  uploadFile: vi.fn(),
};

export const pet = {
  queries: {
    useFindPets: withMockQuery(vi.fn()),
    useFindPetsByTags: withMockQuery(vi.fn()),
    usePetById: withMockQuery(vi.fn()),
  },

  mutations: {
    useAddPet: withMockMutation(vi.fn()),
    useDeletePet: withMockMutation(vi.fn()),
    useUpdatePet: withMockMutation(vi.fn()),
    useUpdatePetWithForm: withMockMutation(vi.fn()),
    useUploadFile: withMockMutation(vi.fn()),
  },

  // queryKeys are pure functions — no mocking needed
  queryKeys: realApi.pet.queryKeys,
};

export const storeClient = {
  deleteOrder: vi.fn(),
  getInventory: vi.fn(),
  getOrderById: vi.fn(),
  placeOrder: vi.fn(),
};

export const store = {
  queries: {
    useInventory: withMockQuery(vi.fn()),
    useOrderById: withMockQuery(vi.fn()),
  },

  mutations: {
    useDeleteOrder: withMockMutation(vi.fn()),
    usePlaceOrder: withMockMutation(vi.fn()),
  },

  // queryKeys are pure functions — no mocking needed
  queryKeys: realApi.store.queryKeys,
};

export const userClient = {
  createUser: vi.fn(),
  createUsersWithListInput: vi.fn(),
  deleteUser: vi.fn(),
  getUserByName: vi.fn(),
  loginUser: vi.fn(),
  logoutUser: vi.fn(),
  updateUser: vi.fn(),
};

export const user = {
  queries: {
    useUserByName: withMockQuery(vi.fn()),
    useLoginUser: withMockQuery(vi.fn()),
    useLogoutUser: withMockQuery(vi.fn()),
  },

  mutations: {
    useCreateUser: withMockMutation(vi.fn()),
    useCreateUsersWithListInput: withMockMutation(vi.fn()),
    useDeleteUser: withMockMutation(vi.fn()),
    useUpdateUser: withMockMutation(vi.fn()),
  },

  // queryKeys are pure functions — no mocking needed
  queryKeys: realApi.user.queryKeys,
};

