/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file
import { type MockInstance, vi } from 'vitest';

import * as realApi from './api';

const defaultQueryReturn = {
  data: undefined, isLoading: false, isPending: false, isFetching: false,
  isSuccess: false, error: null, refetch: vi.fn(), status: 'pending' as const,
};

const defaultMutationReturn = {
  mutate: vi.fn(), mutateAsync: vi.fn(), isPending: false,
  isSuccess: false, error: null, data: undefined, reset: vi.fn(),
};

// ─── TanStack Query mock helpers ─────────────────────────────────────────────

interface MockQueryReturn {
  /** The data to return from the mock */
  data: unknown;
  /** Whether to return a loading state (default: false) */
  isLoading?: boolean;
  /** Whether to return an error (default: undefined) */
  error?: Error | null;
}

/** Augments a spy with a `mockQuery` shorthand for useQuery hooks. */
function withMockQuery<T extends MockInstance>(spy: T) {
  return Object.assign(spy, {
    mockQuery({ data, isLoading, error }: MockQueryReturn) {
      const pending = isLoading ?? false;
      spy.mockReturnValue({
        ...defaultQueryReturn,
        data,
        isLoading: pending,
        isPending: pending,
        isSuccess: data !== undefined && !pending,
        error: error ?? null,
        status: pending ? 'pending' : ('success' as const),
      });
    },
  });
}

interface MockMutationReturn {
  /** The data to return from the mock */
  data: unknown;
  /** Whether to return a mutating state (default: false) */
  isPending?: boolean;
  /** Whether to return an error (default: undefined) */
  error?: Error | null;
}

/** Augments a spy with a `mockMutation` shorthand for useMutation hooks. */
function withMockMutation<T extends MockInstance>(spy: T) {
  return Object.assign(spy, {
    mockMutation({ data, isPending, error }: MockMutationReturn) {
      spy.mockReturnValue({
        ...defaultMutationReturn,
        mutate: vi.fn(),
        mutateAsync: vi.fn(),
        isPending: isPending ?? false,
        error: error ?? null,
        data,
      });
    },
  });
}

export function createClientMocks() {
  return {
    petClient: {
      addPet: vi.spyOn(realApi.petClient, 'addPet').mockReturnValue(undefined as any),
      deletePet: vi.spyOn(realApi.petClient, 'deletePet').mockReturnValue(undefined as any),
      findPets: vi.spyOn(realApi.petClient, 'findPets').mockReturnValue(undefined as any),
      findPetsByTags: vi.spyOn(realApi.petClient, 'findPetsByTags').mockReturnValue(undefined as any),
      getPetById: vi.spyOn(realApi.petClient, 'getPetById').mockReturnValue(undefined as any),
      updatePet: vi.spyOn(realApi.petClient, 'updatePet').mockReturnValue(undefined as any),
      updatePetWithForm: vi.spyOn(realApi.petClient, 'updatePetWithForm').mockReturnValue(undefined as any),
      uploadFile: vi.spyOn(realApi.petClient, 'uploadFile').mockReturnValue(undefined as any),
    },
    storeClient: {
      deleteOrder: vi.spyOn(realApi.storeClient, 'deleteOrder').mockReturnValue(undefined as any),
      getInventory: vi.spyOn(realApi.storeClient, 'getInventory').mockReturnValue(undefined as any),
      getOrderById: vi.spyOn(realApi.storeClient, 'getOrderById').mockReturnValue(undefined as any),
      placeOrder: vi.spyOn(realApi.storeClient, 'placeOrder').mockReturnValue(undefined as any),
    },
    userClient: {
      createUser: vi.spyOn(realApi.userClient, 'createUser').mockReturnValue(undefined as any),
      createUsersWithListInput: vi.spyOn(realApi.userClient, 'createUsersWithListInput').mockReturnValue(undefined as any),
      deleteUser: vi.spyOn(realApi.userClient, 'deleteUser').mockReturnValue(undefined as any),
      getUserByName: vi.spyOn(realApi.userClient, 'getUserByName').mockReturnValue(undefined as any),
      loginUser: vi.spyOn(realApi.userClient, 'loginUser').mockReturnValue(undefined as any),
      logoutUser: vi.spyOn(realApi.userClient, 'logoutUser').mockReturnValue(undefined as any),
      updateUser: vi.spyOn(realApi.userClient, 'updateUser').mockReturnValue(undefined as any),
    },
  };
}

export type ClientMocks = ReturnType<typeof createClientMocks>;

export function createApiHookMocks() {
  return {
    pet: {
      queries: {
        useFindPets: withMockQuery(vi.spyOn(realApi.pet.queries, 'useFindPets').mockReturnValue(defaultQueryReturn as any)),
        useFindPetsByTags: withMockQuery(vi.spyOn(realApi.pet.queries, 'useFindPetsByTags').mockReturnValue(defaultQueryReturn as any)),
        usePetById: withMockQuery(vi.spyOn(realApi.pet.queries, 'usePetById').mockReturnValue(defaultQueryReturn as any)),
      },
      mutations: {
        useAddPet: withMockMutation(vi.spyOn(realApi.pet.mutations, 'useAddPet').mockReturnValue(defaultMutationReturn as any)),
        useDeletePet: withMockMutation(vi.spyOn(realApi.pet.mutations, 'useDeletePet').mockReturnValue(defaultMutationReturn as any)),
        useUpdatePet: withMockMutation(vi.spyOn(realApi.pet.mutations, 'useUpdatePet').mockReturnValue(defaultMutationReturn as any)),
        useUpdatePetWithForm: withMockMutation(vi.spyOn(realApi.pet.mutations, 'useUpdatePetWithForm').mockReturnValue(defaultMutationReturn as any)),
        useUploadFile: withMockMutation(vi.spyOn(realApi.pet.mutations, 'useUploadFile').mockReturnValue(defaultMutationReturn as any)),
      },
    },
    store: {
      queries: {
        useInventory: withMockQuery(vi.spyOn(realApi.store.queries, 'useInventory').mockReturnValue(defaultQueryReturn as any)),
        useOrderById: withMockQuery(vi.spyOn(realApi.store.queries, 'useOrderById').mockReturnValue(defaultQueryReturn as any)),
      },
      mutations: {
        useDeleteOrder: withMockMutation(vi.spyOn(realApi.store.mutations, 'useDeleteOrder').mockReturnValue(defaultMutationReturn as any)),
        usePlaceOrder: withMockMutation(vi.spyOn(realApi.store.mutations, 'usePlaceOrder').mockReturnValue(defaultMutationReturn as any)),
      },
    },
    user: {
      queries: {
        useUserByName: withMockQuery(vi.spyOn(realApi.user.queries, 'useUserByName').mockReturnValue(defaultQueryReturn as any)),
        useLoginUser: withMockQuery(vi.spyOn(realApi.user.queries, 'useLoginUser').mockReturnValue(defaultQueryReturn as any)),
        useLogoutUser: withMockQuery(vi.spyOn(realApi.user.queries, 'useLogoutUser').mockReturnValue(defaultQueryReturn as any)),
      },
      mutations: {
        useCreateUser: withMockMutation(vi.spyOn(realApi.user.mutations, 'useCreateUser').mockReturnValue(defaultMutationReturn as any)),
        useCreateUsersWithListInput: withMockMutation(vi.spyOn(realApi.user.mutations, 'useCreateUsersWithListInput').mockReturnValue(defaultMutationReturn as any)),
        useDeleteUser: withMockMutation(vi.spyOn(realApi.user.mutations, 'useDeleteUser').mockReturnValue(defaultMutationReturn as any)),
        useUpdateUser: withMockMutation(vi.spyOn(realApi.user.mutations, 'useUpdateUser').mockReturnValue(defaultMutationReturn as any)),
      },
    },
  };
}

export type ApiHookMocks = ReturnType<typeof createApiHookMocks>;
