/* istanbul ignore file -- auto-generated test helper */
/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// biome-ignore-all lint: auto-generated code
// deno-lint-ignore-file
import { vi } from 'vitest';

export const petClient = {
  addPet: vi.fn(),
  deletePet: vi.fn(),
  findPets: vi.fn(),
  findPetsByTags: vi.fn(),
  getPetById: vi.fn(),
  updatePet: vi.fn(),
  updatePetWithForm: vi.fn(),
  uploadFile: vi.fn(),
};

export const storeClient = {
  deleteOrder: vi.fn(),
  getInventory: vi.fn(),
  getOrderById: vi.fn(),
  placeOrder: vi.fn(),
};

export const userClient = {
  createUser: vi.fn(),
  createUsersWithListInput: vi.fn(),
  deleteUser: vi.fn(),
  getUserByName: vi.fn(),
  loginUser: vi.fn(),
  logoutUser: vi.fn(),
  updateUser: vi.fn(),
};

