import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const rootDir = path.join(__dirname, '..');
const templatesRootDir = path.join(rootDir, 'templates');
const outputFilePath = path.join(rootDir, 'src', 'generated', 'bundledTemplates.ts');

const templateStore: Record<string, Record<string, string>> = {};

for (const templateName of sortedDirItems(templatesRootDir)) {
  const templateDir = path.join(templatesRootDir, templateName);
  if (!statSync(templateDir).isDirectory()) {
    continue;
  }

  const files: Record<string, string> = {};
  for (const templateFile of sortedDirItems(templateDir)) {
    if (!templateFile.endsWith('.ejs')) {
      continue;
    }

    const fullPath = path.join(templateDir, templateFile);
    files[templateFile] = readFileSync(fullPath, 'utf8');
  }

  templateStore[templateName] = files;
}

const fileContents =
  '// This file is auto-generated by scripts/bundle-templates.ts\n' +
  '// Do not edit this file manually.\n\n' +
  `export const BUNDLED_TEMPLATES = ${JSON.stringify(templateStore, null, 2)} as const;\n\n` +
  'export type BundledTemplateStore = Record<string, Record<string, string>>;\n';

mkdirSync(path.dirname(outputFilePath), { recursive: true });
writeFileSync(outputFilePath, fileContents);

function sortedDirItems(dirPath: string): string[] {
  return readdirSync(dirPath).sort((a, b) => a.localeCompare(b));
}
